'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const { isReviewerAuthored, createCanonicalState, acceptProposal } = require('../utils/canonicalMinutes/state');
const { publishableTopicCards } = require('../utils/canonicalMinutes/topicEditorial');
const { normaliseAndValidateActionOwner } = require('../utils/stagedEditorial');
const { runCanonicalLiveStage } = require('../utils/canonicalMinutes/liveStages');

// The reviewer-correction contract, stated as tests.
//
// The rule is that a value the reviewer confirmed is theirs: it is not reworded, not
// filtered, and not regenerated by a later stage. Everything here is a case that failed
// before the contract existed, so a regression re-breaks a named test rather than quietly
// changing what a client reads.

const DITA_TRANSCRIPT = path.resolve(
  __dirname,
  '../scripts/meeting-minutes-final-golden/021_real_dita_importer_obligations_transcript/transcript.txt'
);

test('reviewer authorship is recognised from confirmation provenance, not from being locked', () => {
  // `locked: true` is stamped on every accepted item including the model's own, so it
  // cannot be the discriminator. Confirmation source is.
  const state = createCanonicalState({ transcriptText: 'x', fileName: 'x.txt', meeting: {} });
  const confirmed = acceptProposal(state, { topics: ['Where the goods physically go'] }, { source: 'stage_1_human_confirmation' });
  const accepted = acceptProposal(state, { topics: ['Goods flow and storage'] });

  assert.equal(confirmed.topics[0].locked, true);
  assert.equal(accepted.topics[0].locked, true, 'locked is set either way, which is why it cannot be the test');
  assert.equal(isReviewerAuthored(confirmed.topics[0]), true);
  assert.equal(isReviewerAuthored(accepted.topics[0]), false);

  assert.equal(isReviewerAuthored({ reviewerAuthored: true }), true);
  assert.equal(isReviewerAuthored({ confirmedTopic: true }), true);
  assert.equal(isReviewerAuthored({ source: 'stage_2_no_edit_acceptance' }), false);
  assert.equal(isReviewerAuthored(null), false);
  assert.equal(isReviewerAuthored('a string'), false);
});

test('the editorial gate never removes a heading the reviewer wrote', () => {
  // Each of these is rejected by isPublishableTopicLabel: a pronoun, a modal, an
  // imperative opener. "CAN bus integration" is rejected for containing the word "can",
  // which is the clearest case that the gate cannot be trusted with a human's wording.
  const headings = [
    'What we owe the client',
    'Actions we agreed',
    'CAN bus integration',
    'Follow-up on the audit'
  ];
  const reviewerCards = headings.map((topic, index) => ({ topic, topicId: `t${index}`, confirmedTopic: true, points: ['a point'] }));
  assert.deepEqual(publishableTopicCards(reviewerCards).map((card) => card.topic), headings);

  const modelCards = headings.map((topic, index) => ({ topic, topicId: `t${index}`, points: ['a point'] }));
  assert.ok(
    publishableTopicCards(modelCards).length < headings.length,
    'the gate must still apply to headings the model produced'
  );
});

test('a reviewer heading is exempt on the path taken when the reviewer confirmed topics', () => {
  // The exemption existed before this contract but keyed off a flag set only by
  // applyConfirmedTopicAgenda, which runs on the branch taken when there is no planned
  // discussion - never on the branch taken because the reviewer confirmed topics. The
  // guard therefore missed precisely the case it was written for.
  const source = fs.readFileSync(path.resolve(__dirname, '../utils/canonicalMinutes/semanticStages.js'), 'utf8');
  const plannedCard = source.slice(source.indexOf('function discussionCardsFromPlan'));
  assert.match(
    plannedCard.slice(0, plannedCard.indexOf('function emergentCardAddsDistinctMeaning')),
    /confirmedTopic:\s*workstream\.provenance === 'reviewer_confirmed'/,
    'cards built from a reviewer-confirmed plan must carry the flag the gate reads'
  );
});

test('an action owner given as a first name resolves against the confirmed attendees', () => {
  const participants = ['Nadia Byrne', 'Mark Kelleher', 'Jacqui Fox'];
  assert.deepEqual(normaliseAndValidateActionOwner('Nadia', participants), { owner: 'Nadia Byrne', status: 'repaired_unambiguous' });
  assert.deepEqual(normaliseAndValidateActionOwner('Nadia Byrne', participants), { owner: 'Nadia Byrne', status: 'accepted' });
  // Without the list there is nothing to resolve against, which is the state the
  // recovered-candidate path was in: every single-name owner became "Not stated", and an
  // owner-less action is then held back by the publication gate.
  assert.equal(normaliseAndValidateActionOwner('Nadia', []).owner, 'Not stated');
  // Ambiguity is still refused rather than guessed.
  assert.equal(normaliseAndValidateActionOwner('Mark', ['Mark Kelleher', 'Mark Deegan']).owner, 'Not stated');
});

test('a recovered action keeps its owner when the meeting uses first names', () => {
  // The gate this feeds drops an action whose owner is "Not stated", so rejecting a lone
  // first name did not merely lose the name - it lost the action. In a meeting where
  // everyone is referred to by first name that was every recovered candidate.
  const { addRecoveredActionCandidates } = require('../utils/canonicalMinutes/trooperPolish');
  const recovered = [{
    owner: 'Nadia',
    action: 'Circulate the DoC pack to the client',
    evidenceAction: 'Circulate the DoC pack to the client',
    evidence: 'Nadia said she would circulate the DoC pack to the client.'
  }];
  const withNames = addRecoveredActionCandidates({
    stagedStage: 'actions',
    _canonicalEvidencePack: [],
    canonicalDiagnostics: { entityNames: ['Nadia Byrne', 'Mark Kelleher'] }
  }, recovered);
  assert.deepEqual(
    withNames._canonicalEvidencePack.map((item) => ({ owner: item.owner, action: item.action })),
    [{ owner: 'Nadia Byrne', action: 'Circulate the DoC pack to the client' }]
  );

  // An owner who is not in the meeting is still not invented into one.
  const withoutNames = addRecoveredActionCandidates({
    stagedStage: 'actions',
    _canonicalEvidencePack: [],
    canonicalDiagnostics: { entityNames: ['Mark Kelleher'] }
  }, recovered);
  assert.equal(withoutNames._canonicalEvidencePack[0].owner, 'Not stated');
});

test('confirmed attendees reach the entity names later stages normalise against', { timeout: 300000 }, () => {
  const transcriptText = fs.readFileSync(DITA_TRANSCRIPT, 'utf8');
  const result = runCanonicalLiveStage(transcriptText, {
    stage: 'summary',
    fileName: 'transcript.txt',
    confirmed: { details: { meetingTitle: 'Importer obligations', internalAttendees: ['Aoife Nic Gearailt'], clientAttendees: [] } }
  });
  assert.ok(
    result.canonicalDiagnostics.entityNames.includes('Aoife Nic Gearailt'),
    'a name the reviewer typed must be available to entity normalisation even when the recorder never spelled it'
  );
});

test('a confirmed meeting purpose survives re-running the summary stage', { timeout: 300000 }, () => {
  const transcriptText = fs.readFileSync(DITA_TRANSCRIPT, 'utf8');
  const meetingPurpose = 'Agree who carries the importer obligations for DITA and what evidence HPRA will expect.';
  const overallTopics = ['Where the goods physically go', 'What HPRA will ask for'];

  const regenerated = runCanonicalLiveStage(transcriptText, {
    stage: 'summary',
    fileName: 'transcript.txt',
    confirmed: {
      details: { meetingTitle: 'Importer obligations' },
      summary: { meetingPurpose, overallTopics, keyFacts: ['Netherlands is used for fiscal clearance only.'] }
    }
  });

  const summary = regenerated.screens.summary;
  assert.equal(summary.meetingPurpose, meetingPurpose, 'the reviewer wrote the purpose; re-running the stage must not replace it');
  assert.equal(summary.meetingPurposeConfirmed, true);
  assert.deepEqual(summary.overallTopics, overallTopics, 'confirmed topics are not re-derived');
  assert.deepEqual(summary.keyFacts, ['Netherlands is used for fiscal clearance only.'], 'key facts must round-trip so the browser is not guarding against the server blanking them');
  assert.deepEqual(summary.topicRefs.map((ref) => ref.text), overallTopics);
});

test('an unconfirmed summary is still generated normally', { timeout: 300000 }, () => {
  // The contract must be inert without confirmed input, or it would suppress the tool's
  // actual job. This is the same assertion the corpus-wide no-edit sweep makes at scale.
  const transcriptText = fs.readFileSync(DITA_TRANSCRIPT, 'utf8');
  const generated = runCanonicalLiveStage(transcriptText, {
    stage: 'summary',
    fileName: 'transcript.txt',
    confirmed: { details: { meetingTitle: 'Importer obligations' } }
  });
  const summary = generated.screens.summary;
  assert.ok(summary.meetingPurpose, 'a purpose is still produced when the reviewer has not written one');
  assert.notEqual(summary.meetingPurposeConfirmed, true);
  assert.ok(summary.overallTopics.length > 0);
  assert.equal(summary.keyFacts, undefined, 'nothing is invented for a field the reviewer never filled in');
});
