import unittest
from pathlib import Path


REPO_DIR = Path(__file__).resolve().parents[1]


class StagedMeetingMinutesContractTest(unittest.TestCase):
    def test_later_staged_steps_use_canonical_pipeline_and_confirmed_state(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")
        staged_editorial = (REPO_DIR / "utils" / "stagedEditorial.js").read_text(encoding="utf-8")

        self.assertIn("async function buildStagedTrooperContext", api)
        self.assertIn("function buildStagedTrooperPrompt", api)
        self.assertIn("function stagedTrooperSchema", api)
        self.assertIn("async function buildStagedGenerationContext", api)
        self.assertIn("stagedFastContextIsUsable", api)
        self.assertIn("let trooperContext = await buildStagedTrooperContext(stage, transcript, req, { evidencePack, workstreamState, actionEvidenceContext })", api)
        self.assertIn("fastContext = await buildStagedMiniLMContext(transcript)", api)
        self.assertIn("buildStagedMiniLMEvidencePack(fastContext", api)
        self.assertIn("AI stage was unavailable", api)
        self.assertIn("CONFIRMED_CONTEXT", api)
        self.assertIn("STAGE_INSTRUCTIONS", api)
        self.assertIn("staged_${stage}_targeted", api)
        self.assertIn("Write stage 2 only", api)
        self.assertIn("function cleanStagedExecutiveSummary", api)
        self.assertIn("project-status narrative", api)
        self.assertIn("where the project actually stands", api)
        self.assertIn("what changed, what was agreed, and what threatens the timeline", api)
        self.assertIn("key discussions covered", api)
        self.assertIn("the reviewer should check", api)
        self.assertIn("filter((sentence) => !/\\bthe reviewer should check\\b/i.test(sentence))", api)
        self.assertIn("buildTightStagedObjectives", api)
        self.assertIn("objectiveReducer", api)
        self.assertIn("maxObjectives: Math.min(7, Math.max(3, topics.length))", api)
        self.assertIn("Alarm changes", api)
        self.assertIn("Language changes", api)
        self.assertIn("Software versioning changes", api)
        self.assertIn("Debug review", api)
        self.assertIn("Change request", api)
        self.assertIn("Write stage 3 only", api)
        self.assertIn("Write stage 4 only", api)
        self.assertIn("Treat CONFIRMED_CONTEXT.overallTopics as the agenda", api)
        self.assertIn("same order as the confirmed overallTopics", api)
        self.assertIn("function alignDiscussionCardsToConfirmedTopics", api)
        self.assertIn("function findDiscussionCardForTopic", api)
        self.assertIn("discussionFallbackForTopic", api)
        self.assertIn("function cleanStagedDiscussionText", api)
        self.assertIn("function consolidateStagedDiscussionPoints", api)
        self.assertIn("function challengeUnsupportedStagedLabels", api)
        self.assertIn("function polishStagedDiscussionCards", api)
        self.assertIn("reshapeStagedDiscussionCardsForHumanMinutes", api)
        self.assertIn("function polishStagedActions", api)
        self.assertIn("function stagedActionIntent", api)
        self.assertIn("function stagedActionsAreDuplicates", api)
        self.assertIn("normaliseFinalStagedActionCandidate", api)
        self.assertIn("stagedFinalActionQualityIssue", staged_editorial)
        self.assertIn("function transcriptPreservedStagedActions", api)
        self.assertIn("function mergePreservedStagedActions", api)
        self.assertIn("function buildStagedActionInventory", api)
        self.assertIn("async function buildStagedEvidenceClassifierContext", api)
        self.assertIn("function actionsFromEvidenceClassifier", api)
        self.assertIn("function attachStagedEvidenceClassifierContext", api)
        self.assertIn("CONFIRMED_CONTEXT.actionInventory", api)
        self.assertIn("CONFIRMED_CONTEXT.actionEvidenceClassifier", api)
        self.assertIn("respect suppression reasons", api)
        self.assertIn("Do not compress actions to a target count", api)
        self.assertIn("Preserve every distinct commitment from actionInventory", api)
        self.assertIn("transcriptActionInventoryCount", api)
        self.assertIn("evidenceClassifierActionCount", api)
        self.assertIn("transcript_action_preservation_guard", api)
        self.assertIn("Complete the risk assessment to develop the audit plan", api)
        self.assertIn("actionPreservation", api)
        self.assertIn("function isAuditableStagedAction", api)
        self.assertIn("function cleanStagedActionText", api)
        self.assertIn("function stripStagedTranscriptArtefacts", api)
        self.assertIn("STAGED_PUBLIC_TIMESTAMP_PATTERN", api)
        self.assertIn("STAGED_PUBLIC_SPEAKER_PATTERN", api)
        self.assertIn("function capitaliseStagedDateMonths", api)
        self.assertIn("function hasStagedSpeakerTurnPrefix", api)
        self.assertIn("function topicEvidenceForStagedDiscussion", api)
        self.assertIn("function buildStagedMiniLMEvidencePack", api)
        self.assertIn("function workstreamEvidenceFitScore", api)
        self.assertIn("function bestWorkstreamForEvidence", api)
        self.assertIn("function reassignStagedEvidencePackByWorkstream", api)
        self.assertIn("function fillMissingStagedWorkstreamEvidence", api)
        self.assertIn("function stagedDiscussionNeedsRetry", api)
        self.assertIn("function missingStagedWorkstreamsFromOutput", api)
        self.assertIn("function filterDiscussionCardsByWorkstreamEvidence", api)
        self.assertIn("function discussionPointEvidenceFitScore", api)
        self.assertIn("function discussionFallbackForWorkstreamState", api)
        self.assertIn("misattributed_discussion_evidence", staged_editorial)
        self.assertIn("function buildStagedWorkstreamState", api)
        self.assertIn("function classifyStagedEvidenceRoles", api)
        self.assertIn("function stagedTextHasPastMarker", api)
        self.assertIn("function stagedTextHasFutureCommitmentMarker", api)
        self.assertIn("function stagedMiniLMEvidenceItems", api)
        self.assertIn("function mergeStagedDiscussionEvidencePack", api)
        self.assertIn("function stagedDiscussionCoverageIsThin", api)
        self.assertIn("topicEvidence: discussionEvidencePack", api)
        self.assertIn("workstreamState: discussionWorkstreamState", api)
        self.assertIn("MiniLM semantic evidence pack", api)
        self.assertIn("CONFIRMED_CONTEXT.workstreamState", api)
        self.assertIn("current status", api)
        self.assertIn("completed/past activity", api)
        self.assertIn("future commitment", api)
        self.assertIn("decision/agreement", api)
        self.assertIn("open point", api)
        self.assertIn("dependency", api)
        self.assertIn("technical detail", api)
        self.assertIn("general chatter/noise", api)
        self.assertIn("Do not convert completed or past activity into a future action", api)
        self.assertIn("explicit actions for the actions stage", api)
        self.assertIn("substantive evidenced workstream", api)
        self.assertIn("abstract_workstream_heading", api)
        self.assertIn("low_heading_evidence_match", api)
        self.assertIn("possible_past_activity_as_action", api)
        self.assertIn("substantive_workstream_omission_risk", api)
        self.assertIn("workstreamStateCount", api)
        self.assertIn("missingWorkstreamCount", api)
        self.assertIn("missingWorkstreams", api)
        self.assertIn("workstreamQualityFlags", api)
        self.assertIn("missing_workstream_recovered", api)
        self.assertIn("workstream_evidence_reassigned", api)
        self.assertIn("competing_workstream_attribution_close", api)
        self.assertIn("reassignedByWorkstreamFit", api)
        self.assertIn("Prefer consolidation over coverage", api)
        self.assertIn("Merge repeated prerequisites", api)
        self.assertIn("For process-heavy topics, preserve the operational sequence", api)
        self.assertIn("Human-style discussion rows should read like minutes", api)
        self.assertIn("Before using labels such as risk, dependency, agreed, confirmed, will or must", api)
        self.assertIn("ordinary sequencing as a risk or dependency", api)
        self.assertIn("auditable verb and object", api)
        self.assertIn("front-end everything", api)
        self.assertIn("Arrange a catch-up meeting", api)
        self.assertIn("Do not turn completed work, general intentions, ongoing workstreams or open points into actions", api)
        self.assertIn("const stagedActions = actionsFromStagedMiniLM", api)
        self.assertIn("const mergedActions = mergePreservedStagedActions", api)
        self.assertIn("normaliseAndValidateActionOwner", api)
        self.assertIn("polishStagedDiscussionCards(cards)", api)
        self.assertIn("stagedDiscussionPointSimilarity", api)
        self.assertIn("stagedDiscussionNeedsRetry", api)
        self.assertIn("fillMissingStagedWorkstreamEvidence", api)
        self.assertIn("Each workstreamState row has already been attribution-scored", api)
        self.assertIn("Do not borrow evidence from another workstream", api)
        self.assertIn("does every bullet belong to this exact workstream", api)
        self.assertIn("omitted evidenced workstreams, or placed evidence under the wrong workstream", api)
        self.assertIn("semantic topic evidence", api)
        self.assertIn("evidencePackTopicCount", api)
        self.assertIn("CONFIRMED_CONTEXT.topicEvidence", api)
        self.assertIn("Do not collapse separate confirmed topics into one combined topic", api)
        self.assertIn("AI discussion output was too thin", api)
        self.assertIn("strictTopicCoverage", api)
        self.assertIn("workstream_state_discussion_fallback", api)
        self.assertIn("droppedMisattributedDiscussionPoints", api)
        self.assertIn("retryCount > originalCount", api)
        self.assertIn("runCanonicalLiveStage", api)
        self.assertIn("canonicalStagedResponse", api)
        self.assertIn("grammarPolishStagedExecutiveSummary", api)
        self.assertIn("executiveSummaryGrammar", api)
        self.assertIn("await grammarPolishStagedExecutiveSummary(presentationSummary)", api)
        self.assertIn("humanConfirmedInputIsAuthoritative", api)
        self.assertIn("return null;", api)
        self.assertIn("const evidenceFilteredDiscussion = filterDiscussionCardsByWorkstreamEvidence", api)
        self.assertIn("compactStagedDiscussionCards(rawDiscussion", api)
        self.assertIn("discussionCompaction", api)
        self.assertIn(": [];", api)
        self.assertIn("glued speaker/timecode prefixes", api)
        self.assertIn('Do not output raw "Name:" or "Name said that..." wording.', api)
        self.assertIn("rewrite them into clear complete sentences without speaker labels or timestamps", api)
        self.assertIn("function isNoEvidenceDiscussionText", api)
        self.assertIn("function structuredDiscussionFromItem", api)
        self.assertIn("executiveSummaryFromFindings", api)
        self.assertIn("Only include a topic if there is substantive transcript evidence", api)
        self.assertIn("omit that topic entirely", api)
        self.assertIn("whatWasDiscussed", api)
        self.assertIn("currentPosition", api)
        self.assertIn("decisionOrAgreement", api)
        self.assertIn("dependencyOrRisk", api)
        self.assertIn("nextStep", api)
        self.assertIn("reviewerGuidance: context.additionalContext", api)
        self.assertIn("do not treat it as transcript evidence", api)
        self.assertIn("additionalContext: firstString", api)
        self.assertIn("additionalContext: input.additionalContext", api)
        self.assertIn("response_format: { type: 'json_object' }", api)
        self.assertIn("router.post('/staged-meeting-minutes/jobs'", api)
        self.assertIn("queueStagedMeetingMinutesStage", api)
        self.assertIn("updateGenerationJobProgress", api)
        self.assertIn("markGenerationJobCompleted", api)
        self.assertIn("markGenerationJobFailure", api)
        self.assertIn("runQueuedStagedMeetingMinutesStage", api)
        self.assertIn("findStagedSourceJobFromRequest", api)
        self.assertIn("function isTransientPgError", db)
        self.assertIn("code === '40P01' || code === '40001'", db)
        self.assertIn("Database query failed after retry.", db)
        self.assertIn("withTransaction(fn, options = {})", db)
        self.assertIn("input_payload->>'draftId'", api)
        self.assertIn("confirmedDetails", api)
        self.assertIn("confirmedSummary", api)
        self.assertIn("confirmedDiscussion", api)
        self.assertIn("confirmedActions", api)
        self.assertIn("parseStagedJsonObject", api)
        self.assertIn("parseStagedJsonArray", api)

    def test_staged_discussion_has_human_minutes_reshaper(self):
        staged_editorial = (REPO_DIR / "utils" / "stagedEditorial.js").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")

        self.assertIn("function reshapeStagedDiscussionCardsForHumanMinutes", staged_editorial)
        self.assertIn("function orderHumanDiscussionPoints", staged_editorial)
        self.assertIn("function topicNeedsProcessDetail", staged_editorial)
        self.assertIn("processDetailPointLimit", staged_editorial)
        self.assertIn("UDI and regulatory data", staged_editorial)
        self.assertIn("EUDAMED", staged_editorial)
        self.assertIn("function finaliseDiscussionPointForMinutes", staged_editorial)
        self.assertIn("raw_transcript_discussion_points_removed", staged_editorial)
        self.assertIn("malformed_discussion_points_removed", staged_editorial)
        self.assertIn("action_only_discussion_points_removed", staged_editorial)
        self.assertIn("STAGED_SPEAKER_TURN_PREFIX", staged_editorial)
        self.assertIn("FIRST_PERSON_TRANSCRIPT_VOICE", staged_editorial)
        self.assertNotIn("clinician|clinical|audible sound", staged_editorial)
        self.assertNotIn("version 1.01 and 1.02", staged_editorial)
        self.assertIn("objectives: context.objectives", api)

    def test_staged_topic_and_owner_cleanup_is_wired(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        trooper = (REPO_DIR / "scripts" / "meeting_minutes_trooper.py").read_text(encoding="utf-8")

        self.assertIn("function isUsableStagedTopic", api)
        self.assertIn("said that|and the other|review these topics", api)
        self.assertIn("function normaliseStagedActionOwner", api)
        self.assertIn("return 'All';", api)
        self.assertIn("def normalise_action_owner", trooper)
        self.assertIn('use "All" as the owner', trooper)

    def test_staged_actions_keep_deadlines_bound_to_source_evidence(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        recovery = (REPO_DIR / "utils" / "stagedActionRecovery.js").read_text(encoding="utf-8")

        self.assertIn("function enrichStagedActionDeadlinesFromTranscript", api)
        self.assertIn("const evidence = String(item?.evidence", api)
        self.assertIn("parseDeadlineEvidence(evidence)", api)
        self.assertIn("sourceTurnIds", recovery)
        self.assertIn("function parseDeadlineEvidence", recovery)
        self.assertIn("end of (?:the|next)", recovery)
        self.assertIn("return enrichStagedActionDeadlinesFromTranscript([...merged, ...preserved], transcriptText);", api)

    def test_staged_eval_replays_real_stage_builders_and_keeps_raw_recovery_text(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        runner = (REPO_DIR / "scripts" / "run_staged_meeting_minutes_eval.js").read_text(encoding="utf-8")
        scorer = (REPO_DIR / "scripts" / "run_meeting_minutes_final_golden_eval.py").read_text(encoding="utf-8")

        self.assertIn("async function runStagedSequenceForEvaluation", api)
        self.assertIn("stagedEvaluationVisibleOutput", api)
        self.assertIn("runCanonicalLiveStage", api)
        self.assertIn("canonicalConfirmedStages", api)
        self.assertIn("confirmedDiscussion", api)
        self.assertIn("runSequence(transcript", runner)
        self.assertIn("deterministicActionInventoryCount", runner)
        self.assertIn("--precomputed-dir", scorer)
        self.assertIn("function attachStagedDecisionsToDiscussionCards", api)
        self.assertIn("card?.decisionOrAgreement", api)

    def test_staged_no_edit_endpoint_returns_browser_review_messages(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")

        self.assertIn("router.post('/staged-meeting-minutes/no-edit-pass'", api)
        self.assertIn("mode: 'no_human_edits'", api)
        self.assertIn("function stagedNoEditReviewExperience", api)
        self.assertIn("Editorial checks (review before moving on)", api)
        self.assertIn("readyForFinalApproval", api)
        self.assertIn("requiredReviewerActions", api)
        self.assertIn("add_to_discussion", api)
        self.assertIn("intentionally_omit", api)
        self.assertIn("return_to_summary_topics", api)
        self.assertIn("Final review would remain locked", api)
        self.assertIn("staged_meeting_minutes_no_edit_pass_completed", api)

    def test_staged_actions_have_final_quality_gate(self):
        staged_editorial = (REPO_DIR / "utils" / "stagedEditorial.js").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")

        self.assertIn("function normaliseFinalStagedActionCandidate", staged_editorial)
        self.assertIn("function stagedFinalActionQualityIssue", staged_editorial)
        self.assertNotIn("missing_owner", staged_editorial)
        self.assertIn("owner: normaliseFinalActionOwner(rewritten.owner)", staged_editorial)
        self.assertIn("missing_actionable_verb", staged_editorial)
        self.assertIn("missing_concrete_object", staged_editorial)
        self.assertIn("transcript_debris", staged_editorial)
        self.assertIn("Review electrical compliance testing outputs and update the final compliance documentation", staged_editorial)
        self.assertIn("function canonicalKnownStagedPersonName", api)
        self.assertIn("STAGED_KNOWN_PERSON_BY_FIRST_NAME", api)
        self.assertIn("function stagedDeadlineIsSupportedByActionEvidence", api)
        self.assertIn("normaliseDeadlineKey", api)
        self.assertIn("mute", api)

    def test_teams_speaker_turns_drive_deterministic_attendee_extraction(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")

        self.assertIn("function extractTeamsTranscriptStructure", api)
        self.assertIn("function extractTeamsTranscriptHeader", api)
        self.assertIn("TEAMS_PERSON_NAME_PATTERN", api)
        self.assertIn("TEAMS_TIMESTAMP_PATTERN", api)
        self.assertIn("TEAMS_HEADER_DATE_PATTERN", api)
        self.assertIn("speakerTurnCounts", api)
        self.assertIn("eventSpeakers", api)
        self.assertIn("started|stopped", api)
        self.assertIn("microsoft_teams_speaker_turns", api)
        self.assertIn("microsoft_teams_header", api)
        self.assertIn("headerDate || normaliseDateInput(rawDate)", api)
        self.assertIn("durationLine", api)
        self.assertIn("attendeeExtraction", api)
        self.assertIn("turnCount: teamsStructure.turnCount", api)
        self.assertIn("dateSource: headerDate ? 'microsoft_teams_header' : 'explicit_or_filename'", api)

    def test_staged_attendee_known_name_mapping_is_wired(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("STAGED_KNOWN_INTERNAL_ATTENDEES", api)
        self.assertIn("STAGED_KNOWN_CLIENT_ATTENDEES", api)
        self.assertIn("function bucketKnownStagedAttendees", api)
        self.assertIn("Colm O’Rourke", api)
        self.assertIn("Jacqui Fox", api)
        self.assertIn("David Didsbury", api)
        self.assertIn("Conor Flynn", api)
        self.assertIn("Claire Nicholson", api)
        self.assertIn("Mark Kelleher", api)
        self.assertIn("John-Paul Hughes", api)
        self.assertIn("Jenny Gough", api)
        self.assertIn("Stuart Smith", api)
        self.assertIn("STAGED_KNOWN_ATTENDEE_ALIASES", api)
        self.assertIn("Smith, Stuart M", api)
        self.assertIn("function canonicalStagedAttendeeAlias", api)
        self.assertIn("function normaliseStagedKnownAttendeeAliasesInText", api)
        self.assertIn("Grace McGroogan", api)
        self.assertIn("Andrew Kane", api)
        self.assertNotIn("'Rebecca Cuckoo'", api)
        self.assertIn("possible_attendee_name_mismatch", api)
        self.assertIn("Orla Skally", api)
        self.assertIn("Abby Lennon", api)
        self.assertIn("...explicitClientBuckets.internal", api)
        self.assertIn("...speakerBuckets.internal", api)
        self.assertIn("...(explicitClientAttendees.length ? [] : speakerBuckets.unknown)", api)
        self.assertIn("knownInternalAttendeeCount", api)
        self.assertIn("knownClientAttendeeCount", api)
        self.assertIn("clientAttendees: attendeesFromRow(clientAttendeesRow)", page)
        self.assertIn("allAttendees: currentParticipants()", page)
        self.assertIn("renderAttendees(clientAttendeesRow, mergedDetails.clientAttendees)", page)
        self.assertNotIn("renderAttendees(clientAttendeesRow, details.allAttendees || details.clientAttendees)", page)

        client_output = (REPO_DIR / "views" / "staged-meeting-minutes-client-output.html").read_text(encoding="utf-8")
        self.assertIn("normaliseList(details.clientAttendees || details.allAttendees)", client_output)
        self.assertNotIn("normaliseList(details.allAttendees || details.clientAttendees)", client_output)

    def test_staged_attendees_and_action_owners_are_editable_from_confirmed_people(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        semantic = (REPO_DIR / "utils" / "canonicalMinutes" / "semanticStages.js").read_text(encoding="utf-8")

        self.assertIn('data-attendee-group="internal"', page)
        self.assertIn('data-attendee-group="client"', page)
        self.assertIn('draggable="true"', page)
        self.assertIn('attendee-drag-handle', page)
        self.assertIn('Drop attendee here', page)
        self.assertIn('contenteditable="true"', page)
        self.assertIn('data-attendee-move', page)
        self.assertIn("row === internalAttendeesRow ? 'Client' : 'Internal'", page)
        self.assertIn("function attendeeStateChanged", page)
        self.assertIn("function attendeeListsFromDetails", page)
        self.assertIn("function mergeGeneratedDetails", page)
        self.assertIn("payload && payload.stagedStage === 'details'", page)
        self.assertIn("attendeeLists.internal.join(', ')", page)
        self.assertIn("function actionOwnerOptions", page)
        self.assertIn('class="action-owner-select"', page)
        self.assertIn("Add someone new…", page)
        self.assertIn("Enter the action owner’s name:", page)
        self.assertIn("A possible commitment still needs an owner", semantic)
        self.assertNotIn("semantic commitment thread(s) require adjudication", semantic)

    def test_post_generation_terminology_qa_is_applied_with_reviewer_undo_and_audited(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        self.assertIn("Check these terms", page)
        self.assertIn("The tool changed ", page)
        self.assertIn("terminology-qa-details", page)
        self.assertIn("terminology-qa-details-body", page)
        self.assertIn("applyAutomaticTerminologyCorrections", page)
        self.assertIn("undoTerminologyCorrection", page)
        self.assertIn("qa-field-highlight", page)
        self.assertIn("decideTerminologySuggestion", page)
        self.assertIn("terminology-qa/suggestions", api)
        self.assertIn("terminology-qa/decision", api)

    def test_staged_review_checks_persist_stable_resolved_keys(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("resolvedReviewCheckKeys", page)
        self.assertIn("function reviewCheckIsResolved(key)", page)
        self.assertIn("resolvedReviewCheckKeys[resolvedKey] = true", page)
        self.assertIn("if (flagResolved) return;", page)
        self.assertIn("resolvedReviewCheckKeys: resolvedReviewCheckKeys", page)
        self.assertIn("existing.resolvedReviewCheckKeys", page)
        self.assertIn("resolveGroupedReviewItems(text.textContent, row, groupedReviewKeys)", page)
        self.assertIn("resolveReviewItem('Reviewed and dismissed transcript snippet.'", page)

    def test_staged_review_analytics_are_persisted_server_side(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")
        migration = (REPO_DIR / "sql" / "migrations" / "20260814_add_staged_review_analytics.sql").read_text(encoding="utf-8")

        self.assertIn("generatedStageVersions", page)
        self.assertIn("reviewAnalyticsPayload", page)
        self.assertIn("/api/staged-meeting-minutes/review-events", page)
        self.assertIn("final_review_completed", page)
        self.assertIn("terminologyDecisionEvents", page)
        self.assertIn("unresolvedWorkstreamList", page)
        self.assertIn("workflowInteractionEvents", page)
        self.assertIn("stage_continue_clicked", page)
        self.assertIn("action_candidate_accepted", page)
        self.assertIn("manual_action_added", page)
        self.assertIn("pdf_download_succeeded", page)
        self.assertIn("workflow_abandonment_signal", page)
        self.assertIn("buildStagedReviewDiffs", api)
        self.assertIn("stagedWorkflowInteractionEvents", api)
        self.assertIn("summariseStagedWorkflowInteractions", api)
        self.assertIn("interactionSummary", api)
        self.assertIn("wording_or_formatting_edit", api)
        self.assertIn("substantive_rewrite", api)
        self.assertIn("structural_or_semantic_change", api)
        self.assertIn("saveStagedMeetingMinutesReviewEvent", db)
        self.assertIn("staged_meeting_minutes_review_events", migration)
        self.assertIn("field_diffs JSONB", migration)
        self.assertIn("regeneration_events JSONB", migration)
        self.assertIn("terminology_decisions JSONB", migration)
        self.assertIn("final_review_completed BOOLEAN", migration)

    def test_staged_transcript_prep_is_deterministic_and_keeps_raw_source(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")

        self.assertIn("function buildPreparedTranscriptForStagedAI", api)
        self.assertIn("deterministic_stage_1_prep", api)
        self.assertIn("transcriptionEvent", api)
        self.assertIn("timestampOnly", api)
        self.assertIn("prepared.push(spoken ? `${speaker}: ${spoken}`", api)
        self.assertIn("function transcriptForStagedAI", api)
        self.assertIn("sourceJob.preparedTranscript", api)
        self.assertIn("canonicalStagedResponse(stage, transcript, input)", api)
        self.assertIn("runCanonicalLiveStage(transcript.text", api)
        self.assertIn("rawTranscriptLength: transcript.text.length", api)
        self.assertIn("preparedTranscriptLength", api)
        self.assertIn("autosavePayload.preparedTranscript", db)
        self.assertIn("preparedTranscript: payload.preparedTranscript || null", db)
        self.assertIn("preparedTranscriptTelemetry: payload.preparedTranscriptTelemetry || null", db)
        self.assertIn("transcript_text, transcript_length", db)

    def test_staged_generation_has_visible_loading_state(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn(".review-status.is-loading", page)
        self.assertIn("animation:spin", page)
        self.assertIn("Generating:", page)
        self.assertIn("Generating summary and topics with AI", page)
        self.assertIn("Elapsed:", page)
        self.assertIn("You can close this tab and resume from Library.", page)
        self.assertIn("isTransientStagePollError", page)
        self.assertIn("Connection hiccup. Still checking the staged generation job", page)
        self.assertIn("maxTransientPollFailures", page)
        self.assertIn("document.body.classList.add('stage-loading')", page)
        self.assertIn("aria-busy", page)
        self.assertIn("https://unpkg.com/lucide@latest/dist/umd/lucide.min.js", page)

    def test_staged_review_uses_guided_locked_stage_flow(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("stage-decision-card", page)
        self.assertIn("Want to move onto the next stage?", page)
        self.assertIn("'Continue to ' + nextLabel.toLowerCase()", page)
        self.assertNotIn("'Yes, generate ' + nextLabel", page)
        self.assertNotIn("'Yes, move to ' + nextLabel", page)
        self.assertIn("No, keep reviewing", page)
        self.assertIn("function highestReachableScreen", page)
        self.assertIn("function lockedStageMessage", page)
        self.assertIn("item.classList.toggle('locked'", page)
        self.assertIn('data-lucide="lock"', page)
        self.assertIn('data-lucide="check"', page)
        self.assertIn("stageAdditionalContext", page)
        self.assertIn('aria-label="Optional context for the next step"', page)
        self.assertIn("formData.append('additionalContext'", page)
        self.assertIn("existing.additionalContext", page)
        self.assertIn("activeIndex === 0 && nextIndex === 1", page)
        self.assertIn("stageNeedsGeneration(target)", page)
        self.assertIn("/api/staged-meeting-minutes/jobs?stage=", page)
        self.assertIn("stageJobId", page)
        self.assertIn("function stagedJobIsStale", page)
        self.assertIn("This staged generation had stalled. Requeuing it safely before resuming", page)
        self.assertIn("'/retry', { method: 'POST' }", page)
        self.assertIn("await pollStageJobUntilDone(stageJobId, resumedStage, targetScreen)", page)
        self.assertNotIn("Opening the job tracker.", page)
        self.assertIn("sourceJobId", page)
        self.assertIn("transcriptText || transcriptFile || storedTranscriptText || stagedSourceJobId || draftId", page)
        self.assertIn("No substantive discussion sections generated", page)
        self.assertIn('class="discussion-table"', page)
        self.assertIn("<th>Topic</th><th>Discussion points</th>", page)
        self.assertIn("discussion-topic-input", page)
        self.assertIn("discussion-points-input", page)
        self.assertIn("cleanDiscussionDisplayText", page)
        self.assertIn("linesFromDiscussionTextarea", page)
        self.assertIn("querySelector('.discussion-topic-input')", page)
        self.assertIn("querySelector('.discussion-points-input')", page)
        self.assertIn('id="addActionRowBtn"', page)
        self.assertIn('data-action-row="duplicate"', page)
        self.assertIn('data-action-row="delete"', page)
        self.assertNotIn("Add topic row", page)
        self.assertNotIn("Reorder topics", page)
        self.assertNotIn("Change owner", page)
        self.assertNotIn("Staging note:", page)
        self.assertNotIn("safeguard-banner", page)
        self.assertNotIn("What was discussed", page)
        self.assertNotIn("Hidden telemetry preview", page)
        self.assertNotIn("Final report preview", page)
        self.assertNotIn("telemetry-panel", page)
        self.assertIn("discussion-card", page)
        self.assertIn("discussion-card-chevron", page)
        self.assertIn('data-lucide="chevron-down"', page)
        self.assertIn('data-discussion-delete', page)
        self.assertIn('data-lucide="trash-2"', page)
        self.assertIn("Are you sure you want to remove this row?", page)
        self.assertIn('id="meetingPurpose"', page)
        self.assertIn('id="keyFactsList"', page)
        self.assertIn('id="actionReviewGroups"', page)
        self.assertIn('id="remainingReviewCount"', page)
        self.assertNotIn('id="reviewToolbar"', page)
        self.assertIn("<th>Owner</th><th>Action</th><th>Due</th>", page)
        self.assertNotIn("<h3>Topics discussed</h3>", page)
        self.assertNotIn(" with no date stated", page)

    def test_staged_transcript_is_carried_across_stages(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        # The transcript is stored in the browser (keyed by draftId) and re-sent for every
        # later stage, and generation streams in place instead of redirecting to Jobs.
        self.assertIn("STAGED_TRANSCRIPTS_KEY", page)
        self.assertIn("function persistTranscript", page)
        self.assertIn("function loadStoredTranscript", page)
        self.assertIn("storedTranscriptText = loadStoredTranscript(draftId)", page)
        self.assertIn("else if (storedTranscriptText) {", page)
        self.assertIn("pollStageJobUntilDone", page)
        self.assertNotIn("window.location.href = payload.jobsUrl", page)

    def test_reviewer_confirmed_purpose_and_key_facts_are_threaded_downstream(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        canonical_state = (REPO_DIR / "utils" / "canonicalMinutes" / "state.js").read_text(encoding="utf-8")
        canonical_live = (REPO_DIR / "utils" / "canonicalMinutes" / "liveStages.js").read_text(encoding="utf-8")
        semantic_stages = (REPO_DIR / "utils" / "canonicalMinutes" / "semanticStages.js").read_text(encoding="utf-8")
        semantic_authority = (REPO_DIR / "utils" / "stagedSemanticAuthority.js").read_text(encoding="utf-8")

        self.assertIn("buildConfirmedUnderstanding", semantic_authority)
        self.assertIn("repairDiscussionForConfirmedUnderstanding", semantic_authority)
        self.assertIn("meetingPurpose: firstString(confirmedSummary.meetingPurpose", api)
        self.assertIn("keyFacts: confirmedUnderstanding.criticalFacts.map((fact) => fact.text)", api)
        self.assertIn("confirmedUnderstanding,", api)
        self.assertIn("Treat CONFIRMED_CONTEXT.confirmedUnderstanding.meetingPurpose", api)
        self.assertIn("Preserve relevant reviewer-confirmed critical facts", api)
        self.assertIn("reviewerConfirmedFactPreservation", api)
        self.assertIn("meetingUnderstanding", canonical_state)
        self.assertIn("const meetingUnderstanding = buildConfirmedUnderstanding(summary)", canonical_live)
        self.assertIn("criticalFacts: meetingUnderstanding.criticalFacts.map((fact) => fact.text)", canonical_live)
        self.assertIn("repairDiscussionForConfirmedUnderstanding", semantic_stages)

    def test_staged_transcript_identity_isolated_between_drafts(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        identity = (REPO_DIR / "utils" / "stagedIdentity.js").read_text(encoding="utf-8")

        self.assertIn("assertStagedSourceIdentity", api)
        self.assertIn("assertStagedTranscriptHash", api)
        self.assertIn("input.transcriptSha256", api)
        self.assertIn("transcriptIdentity.transcriptSha256", api)
        self.assertIn("sourceJob.inputPayload?.draftId", api)
        self.assertIn("sourceJob.inputPayload?.transcriptSha256", api)
        self.assertIn("STAGED_TRANSCRIPT_IDENTITY_MISMATCH", identity)
        self.assertIn("function resetStagedWorkflowForNewTranscript", page)
        self.assertIn("resetStagedWorkflowForNewTranscript();", page)
        self.assertIn("draftTranscriptSha256", page)
        self.assertIn("formData.append('transcriptSha256'", page)
        self.assertIn("window.crypto.randomUUID", page)

    def test_post_extraction_editorial_pass_is_wired_in(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        editorial = (REPO_DIR / "utils" / "stagedEditorial.js").read_text(encoding="utf-8")

        # The editorial helpers live in a dependency-free util so they can be unit
        # tested without the router/db, and are wired into the staged flow.
        self.assertIn("require('../utils/stagedEditorial')", api)
        self.assertIn("isMalformedStagedLine", api)
        self.assertIn("hasStagedDecisionEvidence", api)
        self.assertIn("dedupeStagedDiscussionCards", api)
        self.assertIn("buildStagedValidationFlags", api)

        # Cross-section de-duplication runs after per-card polishing, and the
        # decision/agreement label is dropped without supporting evidence.
        self.assertIn("dedupeStagedDiscussionCards(polished)", api)
        self.assertIn("if (polished.decisionOrAgreement && !hasStagedDecisionEvidence(polished.decisionOrAgreement))", api)
        self.assertIn("if (isMalformedStagedLine(cleaned)) return true;", api)

        # Advisory flags are attached to the staged payloads (never auto-fixed away).
        self.assertIn("validationFlags,", api)
        self.assertIn("function stagedReviewContextFromRequest", api)
        self.assertIn("const reviewContext = stagedReviewContextFromRequest(req)", api)
        self.assertIn("reviewObjectives: input.reviewObjectives || ''", api)
        self.assertIn("reviewDiscussion: input.reviewDiscussion || ''", api)
        self.assertIn("reviewActions: input.reviewActions || ''", api)
        self.assertIn("function serialiseActionReviewCandidate", api)
        self.assertIn("action-candidate-${stableActionCandidateHash(candidate)}", api)
        self.assertIn("resolutionKey: `action-review-candidates:", api)

        # The util exposes the mechanical fixers and the advisory flag builder.
        for name in (
            "function isMalformedStagedLine",
            "function hasStagedDecisionEvidence",
            "function dedupeStagedDiscussionCards",
            "function buildStagedValidationFlags",
        ):
            self.assertIn(name, editorial)
        self.assertIn("duplicate_section", editorial)
        self.assertIn("malformed_text", editorial)
        self.assertIn("possible_omitted_workstream", editorial)

    def test_staged_view_renders_advisory_validation_flags(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("id=\"stageValidationFlags\"", page)
        self.assertIn("function renderValidationFlags", page)
        self.assertIn("function addValidationSuggestionToDiscussion", page)
        self.assertIn("Add to discussion", page)
        self.assertIn("renderValidationFlags(payload && payload.validationFlags, payload && payload.stagedStage, payload && payload.actionReviewCandidates)", page)
        self.assertIn("formData.append('reviewObjectives'", page)
        self.assertIn("formData.append('reviewDiscussion'", page)
        self.assertIn("formData.append('reviewActions'", page)
        self.assertIn("Editorial checks (review before moving on)", page)

    def test_staged_reviewer_copy_and_controls_hide_internal_processing_terms(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")

        self.assertIn("review-check-button", page)
        self.assertIn("review-target-button", page)
        self.assertIn("review-field-note", page)
        self.assertIn("stage-review-targeted", page)
        self.assertIn("Show in table", page)
        self.assertIn("✓ Reviewed", page)
        self.assertIn("review prompt' + (outstanding === 1 ? '' : 's') + ' to check'", page)
        self.assertIn("Actions are grouped below to help you review them.", page)
        self.assertIn("function reviewerFlagMessage", page)
        self.assertIn("function applyReviewFlagAnnotations", page)
        self.assertIn("function focusReviewFlagTarget", page)
        self.assertIn("renderedMessages[messageKey].push(flagKey)", page)
        self.assertIn("resolveGroupedReviewItems", page)
        self.assertIn("You’ve reviewed all editorial checks.", page)
        self.assertIn("function drawAttentionToEditorialChecks", page)
        self.assertIn("editorial-check-flash", page)
        self.assertIn("remainingReviewCount.hidden = activeIndex !== 3 || !outstanding", page)
        self.assertNotIn("Review next item", page)
        self.assertNotIn("nextReviewItemBtn", page)
        self.assertIn("Ready to move onto Summary?", page)
        self.assertIn("Continue when Details looks right, or add anything you’d like the next step to emphasise.", page)
        self.assertNotIn("Anything else to add?", page)
        self.assertIn("stage-autosave-bottom", page)
        self.assertIn("action-candidate-meta", page)
        self.assertIn("' transcript snippet' + (entries.length === 1 ? '' : 's')", page)
        self.assertIn('that may contain actions</summary>', page)
        self.assertIn('Review these snippets and turn any genuine commitments into actions.', page)
        self.assertIn('aria-label="Create action from transcript snippet"', page)
        self.assertIn('aria-label="Dismiss transcript snippet"', page)
        self.assertIn(">Create action</button>", page)
        self.assertIn(">× Dismiss</button>", page)
        self.assertNotIn('Other possible follow-ups', page)
        self.assertIn("function validReviewerOwner", page)
        self.assertIn(">Add owner</option>", page)
        self.assertNotIn("Mark reviewed", page)
        self.assertNotIn("Running canonical ${stage} evidence classification.", api)
        self.assertIn("Reviewing discussion evidence.", api)
        self.assertIn("Reviewing action evidence.", api)

    def test_staged_export_uses_one_server_generated_pdf_for_download_and_preview(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        output = (REPO_DIR / "views" / "staged-meeting-minutes-client-output.html").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        pdf = (REPO_DIR / "utils" / "stagedMinutesPdf.js").read_text(encoding="utf-8")

        self.assertIn('id="exportClientPdfBtn"', page)
        self.assertIn('id="previewClientPdfBtn"', page)
        self.assertIn("function generatedClientPdf", page)
        self.assertIn("/api/staged-meeting-minutes/pdf", page)
        self.assertIn("generatedPdfCache", page)
        self.assertIn("Download PDF", page)
        self.assertIn("Preview PDF", page)
        self.assertIn("router.post('/staged-meeting-minutes/pdf'", api)
        self.assertIn("displayHeaderFooter: false", pdf)
        self.assertIn("Content-Disposition", api)
        self.assertNotIn("Export, email and save are still disabled", page)
        self.assertNotIn("window.print()", page)
        self.assertNotIn("window.print()", output)


if __name__ == "__main__":
    unittest.main()
