import unittest
from pathlib import Path


REPO_DIR = Path(__file__).resolve().parents[1]


class StagedMeetingMinutesContractTest(unittest.TestCase):
    def test_later_staged_steps_use_targeted_trooper_and_keep_fast_fallback(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")

        self.assertIn("async function buildStagedTrooperContext", api)
        self.assertIn("function buildStagedTrooperPrompt", api)
        self.assertIn("function stagedTrooperSchema", api)
        self.assertIn("async function buildStagedGenerationContext", api)
        self.assertIn("stagedFastContextIsUsable", api)
        self.assertIn("let trooperContext = await buildStagedTrooperContext(stage, transcript, req, { evidencePack, workstreamState, actionEvidenceContext })", api)
        self.assertIn("fastContext = await buildStagedMiniLMContext(transcript)", api)
        self.assertIn("buildStagedMiniLMEvidencePack(fastContext", api)
        self.assertIn("AI stage was unavailable", api)
        self.assertIn("CONFIRMED_CONTEXT", api)
        self.assertIn("STAGE_INSTRUCTIONS", api)
        self.assertIn("staged_${stage}_targeted", api)
        self.assertIn("Write stage 2 only", api)
        self.assertIn("function cleanStagedExecutiveSummary", api)
        self.assertIn("project-status narrative", api)
        self.assertIn("where the project actually stands", api)
        self.assertIn("what changed, what was agreed, and what threatens the timeline", api)
        self.assertIn("key discussions covered", api)
        self.assertIn("the reviewer should check", api)
        self.assertIn("filter((sentence) => !/\\bthe reviewer should check\\b/i.test(sentence))", api)
        self.assertIn("buildTightStagedObjectives", api)
        self.assertIn("objectiveReducer", api)
        self.assertIn("maxObjectives: Math.min(7, Math.max(3, topics.length))", api)
        self.assertIn("Alarm changes", api)
        self.assertIn("Language changes", api)
        self.assertIn("Software versioning changes", api)
        self.assertIn("Debug review", api)
        self.assertIn("Change request", api)
        self.assertIn("Write stage 3 only", api)
        self.assertIn("Write stage 4 only", api)
        self.assertIn("Treat CONFIRMED_CONTEXT.overallTopics as the agenda", api)
        self.assertIn("same order as the confirmed overallTopics", api)
        self.assertIn("function alignDiscussionCardsToConfirmedTopics", api)
        self.assertIn("function findDiscussionCardForTopic", api)
        self.assertIn("discussionFallbackForTopic", api)
        self.assertIn("function cleanStagedDiscussionText", api)
        self.assertIn("function consolidateStagedDiscussionPoints", api)
        self.assertIn("function challengeUnsupportedStagedLabels", api)
        self.assertIn("function polishStagedDiscussionCards", api)
        self.assertIn("function polishStagedActions", api)
        self.assertIn("function stagedActionIntent", api)
        self.assertIn("function stagedActionsAreDuplicates", api)
        self.assertIn("function transcriptPreservedStagedActions", api)
        self.assertIn("function mergePreservedStagedActions", api)
        self.assertIn("function buildStagedActionInventory", api)
        self.assertIn("async function buildStagedEvidenceClassifierContext", api)
        self.assertIn("function actionsFromEvidenceClassifier", api)
        self.assertIn("function attachStagedEvidenceClassifierContext", api)
        self.assertIn("CONFIRMED_CONTEXT.actionInventory", api)
        self.assertIn("CONFIRMED_CONTEXT.actionEvidenceClassifier", api)
        self.assertIn("respect suppression reasons", api)
        self.assertIn("Do not compress actions to a target count", api)
        self.assertIn("Preserve every distinct commitment from actionInventory", api)
        self.assertIn("transcriptActionInventoryCount", api)
        self.assertIn("evidenceClassifierActionCount", api)
        self.assertIn("transcript_action_preservation_guard", api)
        self.assertIn("Complete the risk assessment to develop the audit plan", api)
        self.assertIn("actionPreservation", api)
        self.assertIn("function isAuditableStagedAction", api)
        self.assertIn("function cleanStagedActionText", api)
        self.assertIn("function stripStagedTranscriptArtefacts", api)
        self.assertIn("STAGED_PUBLIC_TIMESTAMP_PATTERN", api)
        self.assertIn("STAGED_PUBLIC_SPEAKER_PATTERN", api)
        self.assertIn("function capitaliseStagedDateMonths", api)
        self.assertIn("function hasStagedSpeakerTurnPrefix", api)
        self.assertIn("function topicEvidenceForStagedDiscussion", api)
        self.assertIn("function buildStagedMiniLMEvidencePack", api)
        self.assertIn("function workstreamEvidenceFitScore", api)
        self.assertIn("function bestWorkstreamForEvidence", api)
        self.assertIn("function reassignStagedEvidencePackByWorkstream", api)
        self.assertIn("function fillMissingStagedWorkstreamEvidence", api)
        self.assertIn("function stagedDiscussionNeedsRetry", api)
        self.assertIn("function missingStagedWorkstreamsFromOutput", api)
        self.assertIn("function buildStagedWorkstreamState", api)
        self.assertIn("function classifyStagedEvidenceRoles", api)
        self.assertIn("function stagedTextHasPastMarker", api)
        self.assertIn("function stagedTextHasFutureCommitmentMarker", api)
        self.assertIn("function stagedMiniLMEvidenceItems", api)
        self.assertIn("function mergeStagedDiscussionEvidencePack", api)
        self.assertIn("function stagedDiscussionCoverageIsThin", api)
        self.assertIn("topicEvidence: discussionEvidencePack", api)
        self.assertIn("workstreamState: discussionWorkstreamState", api)
        self.assertIn("MiniLM semantic evidence pack", api)
        self.assertIn("CONFIRMED_CONTEXT.workstreamState", api)
        self.assertIn("current status", api)
        self.assertIn("completed/past activity", api)
        self.assertIn("future commitment", api)
        self.assertIn("decision/agreement", api)
        self.assertIn("open point", api)
        self.assertIn("dependency", api)
        self.assertIn("technical detail", api)
        self.assertIn("general chatter/noise", api)
        self.assertIn("Do not convert completed or past activity into a future action", api)
        self.assertIn("explicit actions for the actions stage", api)
        self.assertIn("substantive evidenced workstream", api)
        self.assertIn("abstract_workstream_heading", api)
        self.assertIn("low_heading_evidence_match", api)
        self.assertIn("possible_past_activity_as_action", api)
        self.assertIn("substantive_workstream_omission_risk", api)
        self.assertIn("workstreamStateCount", api)
        self.assertIn("missingWorkstreamCount", api)
        self.assertIn("missingWorkstreams", api)
        self.assertIn("workstreamQualityFlags", api)
        self.assertIn("missing_workstream_recovered", api)
        self.assertIn("workstream_evidence_reassigned", api)
        self.assertIn("competing_workstream_attribution_close", api)
        self.assertIn("reassignedByWorkstreamFit", api)
        self.assertIn("Prefer consolidation over coverage", api)
        self.assertIn("Merge repeated prerequisites", api)
        self.assertIn("Before using labels such as risk, dependency, agreed, confirmed, will or must", api)
        self.assertIn("ordinary sequencing as a risk or dependency", api)
        self.assertIn("auditable verb and object", api)
        self.assertIn("front-end everything", api)
        self.assertIn("Arrange a catch-up meeting", api)
        self.assertIn("Do not turn completed work, general intentions, ongoing workstreams or open points into actions", api)
        self.assertIn("const stagedActions = actionsFromStagedMiniLM", api)
        self.assertIn("const actions = mergePreservedStagedActions", api)
        self.assertIn("polishStagedDiscussionCards(cards)", api)
        self.assertIn("stagedDiscussionPointSimilarity", api)
        self.assertIn("stagedDiscussionNeedsRetry", api)
        self.assertIn("fillMissingStagedWorkstreamEvidence", api)
        self.assertIn("Each workstreamState row has already been attribution-scored", api)
        self.assertIn("Do not borrow evidence from another workstream", api)
        self.assertIn("does every bullet belong to this exact workstream", api)
        self.assertIn("omitted evidenced workstreams, or placed evidence under the wrong workstream", api)
        self.assertIn("semantic topic evidence", api)
        self.assertIn("evidencePackTopicCount", api)
        self.assertIn("CONFIRMED_CONTEXT.topicEvidence", api)
        self.assertIn("Do not collapse separate confirmed topics into one combined topic", api)
        self.assertIn("AI discussion output was too thin", api)
        self.assertIn("strictTopicCoverage", api)
        self.assertIn("retryCount > originalCount", api)
        self.assertIn("buildStagedGenerationContext('discussion'", api)
        self.assertIn("return null;", api)
        self.assertIn("const rawDiscussion = miniLmDiscussion.length", api)
        self.assertIn("compactStagedDiscussionCards(rawDiscussion", api)
        self.assertIn("discussionCompaction", api)
        self.assertIn(": [];", api)
        self.assertIn("glued speaker/timecode prefixes", api)
        self.assertIn('Do not output raw "Name:" or "Name said that..." wording.', api)
        self.assertIn("rewrite them into clear complete sentences without speaker labels or timestamps", api)
        self.assertIn("function isNoEvidenceDiscussionText", api)
        self.assertIn("function structuredDiscussionFromItem", api)
        self.assertIn("executiveSummaryFromFindings", api)
        self.assertIn("Only include a topic if there is substantive transcript evidence", api)
        self.assertIn("omit that topic entirely", api)
        self.assertIn("whatWasDiscussed", api)
        self.assertIn("currentPosition", api)
        self.assertIn("decisionOrAgreement", api)
        self.assertIn("dependencyOrRisk", api)
        self.assertIn("nextStep", api)
        self.assertIn("reviewerGuidance: context.additionalContext", api)
        self.assertIn("do not treat it as transcript evidence", api)
        self.assertIn("additionalContext: firstString", api)
        self.assertIn("additionalContext: input.additionalContext", api)
        self.assertIn("response_format: { type: 'json_object' }", api)
        self.assertIn("router.post('/staged-meeting-minutes/jobs'", api)
        self.assertIn("queueStagedMeetingMinutesStage", api)
        self.assertIn("updateGenerationJobProgress", api)
        self.assertIn("markGenerationJobCompleted", api)
        self.assertIn("markGenerationJobFailure", api)
        self.assertIn("runQueuedStagedMeetingMinutesStage", api)
        self.assertIn("findStagedSourceJobFromRequest", api)
        self.assertIn("function isTransientPgError", db)
        self.assertIn("code === '40P01' || code === '40001'", db)
        self.assertIn("Database query failed after retry.", db)
        self.assertIn("withTransaction(fn, options = {})", db)
        self.assertIn("input_payload->>'draftId'", api)
        self.assertIn("confirmedDetails", api)
        self.assertIn("confirmedSummary", api)
        self.assertIn("confirmedDiscussion", api)
        self.assertIn("confirmedActions", api)
        self.assertIn("parseStagedJsonObject", api)
        self.assertIn("parseStagedJsonArray", api)

    def test_staged_topic_and_owner_cleanup_is_wired(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        trooper = (REPO_DIR / "scripts" / "meeting_minutes_trooper.py").read_text(encoding="utf-8")

        self.assertIn("function isUsableStagedTopic", api)
        self.assertIn("said that|and the other|review these topics", api)
        self.assertIn("function normaliseStagedActionOwner", api)
        self.assertIn("return 'All';", api)
        self.assertIn("def normalise_action_owner", trooper)
        self.assertIn('use "All" as the owner', trooper)

    def test_staged_actions_enrich_deadlines_from_grounded_transcript_windows(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")

        self.assertIn("function enrichStagedActionDeadlinesFromTranscript", api)
        self.assertIn("function inferredDeadlineForStagedAction", api)
        self.assertIn("function stagedDeadlineEvidenceWindows", api)
        self.assertIn("overlap >= 2", api)
        self.assertIn("before (?:the )?(?:audit|site visit|next review|client call|meeting)", api)
        self.assertIn("return enrichStagedActionDeadlinesFromTranscript([...merged, ...preserved], transcriptText);", api)

    def test_teams_speaker_turns_drive_deterministic_attendee_extraction(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")

        self.assertIn("function extractTeamsTranscriptStructure", api)
        self.assertIn("function extractTeamsTranscriptHeader", api)
        self.assertIn("TEAMS_PERSON_NAME_PATTERN", api)
        self.assertIn("TEAMS_TIMESTAMP_PATTERN", api)
        self.assertIn("TEAMS_HEADER_DATE_PATTERN", api)
        self.assertIn("speakerTurnCounts", api)
        self.assertIn("eventSpeakers", api)
        self.assertIn("started|stopped", api)
        self.assertIn("microsoft_teams_speaker_turns", api)
        self.assertIn("microsoft_teams_header", api)
        self.assertIn("headerDate || normaliseDateInput(rawDate)", api)
        self.assertIn("durationLine", api)
        self.assertIn("attendeeExtraction", api)
        self.assertIn("turnCount: teamsStructure.turnCount", api)
        self.assertIn("dateSource: headerDate ? 'microsoft_teams_header' : 'explicit_or_filename'", api)

    def test_staged_transcript_prep_is_deterministic_and_keeps_raw_source(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")

        self.assertIn("function buildPreparedTranscriptForStagedAI", api)
        self.assertIn("deterministic_stage_1_prep", api)
        self.assertIn("transcriptionEvent", api)
        self.assertIn("timestampOnly", api)
        self.assertIn("prepared.push(spoken ? `${speaker}: ${spoken}`", api)
        self.assertIn("function transcriptForStagedAI", api)
        self.assertIn("sourceJob.preparedTranscript", api)
        self.assertIn("const aiTranscript = transcriptForStagedAI(transcript, input)", api)
        self.assertIn("buildStagedGenerationContext(stage, aiTranscript", api)
        self.assertIn("rawTranscriptLength: transcript.text.length", api)
        self.assertIn("preparedTranscriptLength", api)
        self.assertIn("autosavePayload.preparedTranscript", db)
        self.assertIn("preparedTranscript: payload.preparedTranscript || null", db)
        self.assertIn("preparedTranscriptTelemetry: payload.preparedTranscriptTelemetry || null", db)
        self.assertIn("transcript_text, transcript_length", db)

    def test_staged_generation_has_visible_loading_state(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn(".review-status.is-loading", page)
        self.assertIn("animation:spin", page)
        self.assertIn("Generating:", page)
        self.assertIn("Generating summary and topics with AI", page)
        self.assertIn("Elapsed:", page)
        self.assertIn("You can close this tab and resume from Jobs.", page)
        self.assertIn("document.body.classList.add('stage-loading')", page)
        self.assertIn("aria-busy", page)
        self.assertIn("https://unpkg.com/lucide@latest/dist/umd/lucide.min.js", page)

    def test_staged_review_uses_guided_locked_stage_flow(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("stage-decision-card", page)
        self.assertIn("Want to move onto the next stage?", page)
        self.assertIn("Yes, proceed to next step", page)
        self.assertNotIn("'Yes, generate ' + nextLabel", page)
        self.assertNotIn("'Yes, move to ' + nextLabel", page)
        self.assertIn("No, keep reviewing", page)
        self.assertIn("function highestReachableScreen", page)
        self.assertIn("function lockedStageMessage", page)
        self.assertIn("item.classList.toggle('locked'", page)
        self.assertIn('data-lucide="lock"', page)
        self.assertIn('data-lucide="check"', page)
        self.assertIn("stageAdditionalContext", page)
        self.assertIn("Anything else to add?", page)
        self.assertIn("formData.append('additionalContext'", page)
        self.assertIn("existing.additionalContext", page)
        self.assertIn("activeIndex === 0 && nextIndex === 1", page)
        self.assertIn("stageNeedsGeneration(target)", page)
        self.assertIn("/api/staged-meeting-minutes/jobs?stage=", page)
        self.assertIn("stageJobId", page)
        self.assertIn("sourceJobId", page)
        self.assertIn("transcriptText || transcriptFile || storedTranscriptText || stagedSourceJobId || draftId", page)
        self.assertIn("No substantive discussion sections generated", page)
        self.assertIn('class="discussion-table"', page)
        self.assertIn("<th>Topic</th><th>Discussion points</th>", page)
        self.assertIn("discussion-topic-input", page)
        self.assertIn("discussion-points-input", page)
        self.assertIn("cleanDiscussionDisplayText", page)
        self.assertIn("linesFromDiscussionTextarea", page)
        self.assertIn("querySelector('input, textarea')", page)
        self.assertIn("querySelector('textarea')", page)
        self.assertIn('id="addActionRowBtn"', page)
        self.assertIn('data-action-row="duplicate"', page)
        self.assertIn('data-action-row="delete"', page)
        self.assertNotIn("Add topic row", page)
        self.assertNotIn("Reorder topics", page)
        self.assertNotIn("Change owner", page)
        self.assertNotIn("Staging note:", page)
        self.assertNotIn("safeguard-banner", page)
        self.assertNotIn("What was discussed", page)
        self.assertNotIn("Hidden telemetry preview", page)
        self.assertNotIn("Final report preview", page)
        self.assertNotIn("telemetry-panel", page)
        self.assertNotIn("discussion-card", page)
        self.assertIn("<th>Owner</th><th>Action</th><th>Due</th>", page)
        self.assertNotIn("<h3>Topics discussed</h3>", page)
        self.assertNotIn(" with no date stated", page)

    def test_staged_transcript_is_carried_across_stages(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        # The transcript is stored in the browser (keyed by draftId) and re-sent for every
        # later stage, and generation streams in place instead of redirecting to Jobs.
        self.assertIn("STAGED_TRANSCRIPTS_KEY", page)
        self.assertIn("function persistTranscript", page)
        self.assertIn("function loadStoredTranscript", page)
        self.assertIn("storedTranscriptText = loadStoredTranscript(draftId)", page)
        self.assertIn("else if (storedTranscriptText) {", page)
        self.assertIn("pollStageJobUntilDone", page)
        self.assertNotIn("window.location.href = payload.jobsUrl", page)

    def test_post_extraction_editorial_pass_is_wired_in(self):
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        editorial = (REPO_DIR / "utils" / "stagedEditorial.js").read_text(encoding="utf-8")

        # The editorial helpers live in a dependency-free util so they can be unit
        # tested without the router/db, and are wired into the staged flow.
        self.assertIn("require('../utils/stagedEditorial')", api)
        self.assertIn("isMalformedStagedLine", api)
        self.assertIn("hasStagedDecisionEvidence", api)
        self.assertIn("dedupeStagedDiscussionCards", api)
        self.assertIn("buildStagedValidationFlags", api)

        # Cross-section de-duplication runs after per-card polishing, and the
        # decision/agreement label is dropped without supporting evidence.
        self.assertIn("dedupeStagedDiscussionCards(polished)", api)
        self.assertIn("if (polished.decisionOrAgreement && !hasStagedDecisionEvidence(polished.decisionOrAgreement))", api)
        self.assertIn("if (isMalformedStagedLine(cleaned)) return true;", api)

        # Advisory flags are attached to the staged payloads (never auto-fixed away).
        self.assertIn("validationFlags,", api)
        self.assertIn("function stagedReviewContextFromRequest", api)
        self.assertIn("const reviewContext = stagedReviewContextFromRequest(req)", api)
        self.assertIn("reviewObjectives: input.reviewObjectives || ''", api)
        self.assertIn("reviewDiscussion: input.reviewDiscussion || ''", api)
        self.assertIn("reviewActions: input.reviewActions || ''", api)

        # The util exposes the mechanical fixers and the advisory flag builder.
        for name in (
            "function isMalformedStagedLine",
            "function hasStagedDecisionEvidence",
            "function dedupeStagedDiscussionCards",
            "function buildStagedValidationFlags",
        ):
            self.assertIn(name, editorial)
        self.assertIn("duplicate_section", editorial)
        self.assertIn("malformed_text", editorial)
        self.assertIn("possible_omitted_workstream", editorial)

    def test_staged_view_renders_advisory_validation_flags(self):
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("id=\"stageValidationFlags\"", page)
        self.assertIn("function renderValidationFlags", page)
        self.assertIn("renderValidationFlags(payload && payload.validationFlags)", page)
        self.assertIn("formData.append('reviewObjectives'", page)
        self.assertIn("formData.append('reviewDiscussion'", page)
        self.assertIn("formData.append('reviewActions'", page)
        self.assertIn("Editorial checks (review before moving on)", page)

    def test_staged_export_uses_clean_client_output_view(self):
        server = (REPO_DIR / "server.js").read_text(encoding="utf-8")
        page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        output = (REPO_DIR / "views" / "staged-meeting-minutes-client-output.html").read_text(encoding="utf-8")

        self.assertIn("app.get('/staged-meeting-minutes/client-output'", server)
        self.assertIn('id="exportClientPdfBtn"', page)
        self.assertIn("function openClientPdfExport", page)
        self.assertIn("/staged-meeting-minutes/client-output?draftId=", page)
        self.assertIn("Export opens a clean client-facing copy without the review controls.", page)
        self.assertNotIn("Export, email and save are still disabled", page)

        self.assertIn("STAGED_DRAFTS_KEY = 'stagedMeetingMinutesJobs'", output)
        self.assertIn("Meeting minutes", output)
        self.assertIn("trinzologo", output.replace("-", "").lower())
        self.assertIn("@media print", output)
        self.assertIn(".toolbar", output)
        self.assertIn("window.print()", output)
        self.assertIn("Review and approve before sharing externally.", output)
        self.assertNotIn("stage-decision-card", output)
        self.assertNotIn("status-strip", output)


if __name__ == "__main__":
    unittest.main()
