import unittest
from pathlib import Path


REPO_DIR = Path(__file__).resolve().parents[1]


class FrontendContractTest(unittest.TestCase):
    def test_meeting_minutes_final_uses_date_picker_for_meeting_date(self):
        shared_js = (REPO_DIR / "public" / "test-transcript-page.js").read_text(encoding="utf-8")

        self.assertIn("function toDateInputValue", shared_js)
        self.assertIn('id="meetingDateInput" type="date"', shared_js)
        self.assertIn("toDateInputValue(schemaOutput.meetingDate)", shared_js)

    def test_feedback_widget_is_scoped_to_meeting_minutes_final(self):
        meeting_minutes_final = (REPO_DIR / "views" / "meeting-minutes-final.html").read_text(encoding="utf-8")
        dashboard = (REPO_DIR / "views" / "dashboard.html").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")

        self.assertIn('id="feedbackWidgetButton"', meeting_minutes_final)
        self.assertIn("/api/meeting-minutes-final/feedback", meeting_minutes_final)
        self.assertIn("Please avoid sharing transcript content", meeting_minutes_final)
        self.assertIn(".feedback-backdrop.hidden { display:none; }", meeting_minutes_final)
        self.assertNotIn("Please don’t paste transcripts or sensitive meeting details here.", meeting_minutes_final)
        self.assertNotIn('id="feedbackEmail"', meeting_minutes_final)
        self.assertNotIn('id="feedbackWidgetButton"', dashboard)
        self.assertIn("router.post('/meeting-minutes-final/feedback'", api)
        self.assertIn("saveMeetingMinutesFeedback", api)
        self.assertIn("meeting_minutes_feedback", db)
        self.assertNotIn("transcriptText", api.split("router.post('/meeting-minutes-final/feedback'", 1)[1].split("router.post('/project-update-test'", 1)[0])

    def test_snippet_level_feedback_and_ai_shortcuts_are_wired(self):
        meeting_minutes_final = (REPO_DIR / "views" / "meeting-minutes-final.html").read_text(encoding="utf-8")
        shared_js = (REPO_DIR / "public" / "test-transcript-page.js").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")

        self.assertIn("snippetImproveEndpoint: '/api/meeting-minutes-final/improve-snippet'", meeting_minutes_final)
        self.assertIn('id="feedbackSnippetQuote"', meeting_minutes_final)
        self.assertIn("event.key.toLowerCase() === 'f'", meeting_minutes_final)
        self.assertIn("Selected snippet for this feedback", meeting_minutes_final)
        self.assertIn("What should change about the selected snippet?", meeting_minutes_final)
        self.assertIn("selectedSnippet: currentSnippet", meeting_minutes_final)
        self.assertNotIn("Feedback about selected snippet", meeting_minutes_final)
        self.assertIn("function getEditableSnippetSelection", shared_js)
        self.assertIn("Ctrl+Shift+M (Cmd+Shift+M on Mac)", shared_js)
        self.assertIn("selection.replace(improved)", shared_js)
        self.assertIn("router.post('/meeting-minutes-final/improve-snippet'", api)
        self.assertIn("selectedSnippet: selectedSnippet || null", api)
        self.assertIn("meeting_minutes_rewrite_snippet.py", api)

    def test_feedback_listing_is_authenticated_and_editable(self):
        server = (REPO_DIR / "server.js").read_text(encoding="utf-8")
        auth = (REPO_DIR / "routes" / "auth.js").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")
        listing = (REPO_DIR / "views" / "meeting-minutes-feedback.html").read_text(encoding="utf-8")
        login = (REPO_DIR / "views" / "auth-login.html").read_text(encoding="utf-8")

        self.assertIn("app.get('/meeting-minutes-feedback', authRoutes.requireAuth", server)
        self.assertIn("router.requireAuth = requireAuth", auth)
        self.assertIn("router.get('/meeting-minutes-final/feedback-submissions', requireAuth", api)
        self.assertIn("router.patch('/meeting-minutes-final/feedback-submissions/:feedbackId', requireAuth", api)
        self.assertIn("router.delete('/meeting-minutes-final/feedback-submissions/:feedbackId', requireAuth", api)
        self.assertIn("listMeetingMinutesFeedback", db)
        self.assertIn("updateMeetingMinutesFeedback", db)
        self.assertIn("deleteMeetingMinutesFeedback", db)
        feedback_list_section = db.split("async function listMeetingMinutesFeedback", 1)[1].split("async function getMeetingMinutesFeedback", 1)[0]
        feedback_detail_section = db.split("async function getMeetingMinutesFeedback", 1)[1].split("async function updateMeetingMinutesFeedback", 1)[0]
        feedback_delete_section = db.split("async function deleteMeetingMinutesFeedback", 1)[1].split("async function getMeetingStatus", 1)[0]
        self.assertIn("LIMIT $1", feedback_list_section)
        self.assertIn("WHERE id = $1", feedback_detail_section)
        self.assertIn("WHERE id = $1 RETURNING id", feedback_delete_section)
        self.assertNotIn("LIMIT ${safeLimit}", feedback_list_section)
        self.assertNotIn("WHERE id = ${id}", feedback_detail_section)
        self.assertNotIn("WHERE id = ${id}", feedback_delete_section)
        self.assertIn("isActive === 't' || isActive === 'true'", db)
        self.assertIn("selectedSnippet", db)
        self.assertIn("claire_comments", db)
        self.assertIn("fix_details", db)
        self.assertIn("/api/meeting-minutes-final/feedback-submissions", listing)
        self.assertIn("Comments from Claire", listing)
        self.assertIn("Fix details", listing)
        self.assertIn("delete-feedback", listing)
        self.assertIn("This action cannot be undone, are you sure you want to delete the feedback?", listing)
        self.assertIn("details class=\"technical-context\"", listing)
        self.assertIn("<summary><h2>Technical context</h2></summary>", listing)
        self.assertIn("Self-registration is disabled", auth)
        self.assertIn("res.redirect('/auth/login')", server)
        self.assertNotIn("Create account", login)
        self.assertNotIn("/auth/register", login)

    def test_dashboard_only_links_to_feedback_listing_and_matches_final_style(self):
        dashboard = (REPO_DIR / "views" / "dashboard.html").read_text(encoding="utf-8")
        meeting_minutes_final = (REPO_DIR / "views" / "meeting-minutes-final.html").read_text(encoding="utf-8")
        shared_nav = (REPO_DIR / "public" / "trinzo.js").read_text(encoding="utf-8")

        shared_style_tokens = ["--bg:#0b1020", "--panel:#11192f", "--accent:#17D0C4", "linear-gradient(145deg,var(--panel),var(--panel2))"]
        for token in shared_style_tokens:
            self.assertIn(token, dashboard)
            self.assertIn(token, meeting_minutes_final)

        self.assertIn("Project Updates", shared_nav)
        self.assertIn("Choose project", shared_nav)
        self.assertNotIn("Choose a project", shared_nav)
        self.assertIn('href="/meeting-minutes-feedback"', dashboard)
        self.assertIn("Open feedback listing", dashboard)
        self.assertNotIn('href="/"', dashboard)
        self.assertNotIn('href="/review"', dashboard)
        self.assertNotIn('href="/meetings"', dashboard)
        self.assertNotIn('href="/auth"', dashboard)
        self.assertNotIn("Transcript workflow", dashboard)
        self.assertNotIn("Review editor", dashboard)
        self.assertNotIn("Meeting manager", dashboard)
        self.assertNotIn("Auth center", dashboard)


    def test_meeting_minutes_golden_eval_defaults_to_live_trooper_route(self):
        runner = (REPO_DIR / "scripts" / "run_meeting_minutes_final_golden_eval.py").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        readme = (REPO_DIR / "scripts" / "meeting-minutes-final-golden" / "README.md").read_text(encoding="utf-8")
        runbook = (REPO_DIR / "scripts" / "meeting-minutes-final-golden" / "RUNBOOK.md").read_text(encoding="utf-8")

        self.assertIn("runPythonTranscriptScript('meeting_minutes_trooper.py'", api)
        self.assertIn('DEFAULT_EXTRACTOR_NAME = "meeting_minutes_trooper.py"', runner)
        self.assertIn('meeting_minutes_trooper.py', readme)
        self.assertIn('meeting_minutes_trooper.py', runbook)
        default_section = runner.split('DEFAULT_EXTRACTOR_NAME', 1)[1].split('REQUIRED_CATEGORIES', 1)[0]
        self.assertNotIn('meeting_minutes_final_colab.py', default_section)

    def test_login_removes_forgot_password_and_secure_auth_copy(self):
        login = (REPO_DIR / "views" / "auth-login.html").read_text(encoding="utf-8")

        self.assertNotIn("Forgot password", login)
        self.assertNotIn("/auth/forgot-password", login)
        self.assertNotIn("Trinzo secure authentication", login)

    def test_login_password_visibility_toggle_is_wired(self):
        login = (REPO_DIR / "views" / "auth-login.html").read_text(encoding="utf-8")

        self.assertIn('class="password-input"', login)
        self.assertIn('id="passwordToggle"', login)
        self.assertIn('type="button"', login)
        self.assertIn('aria-label="Show password"', login)
        self.assertIn('aria-pressed="false"', login)
        self.assertIn("passwordInput.type = isVisible ? 'password' : 'text'", login)
        self.assertIn("passwordToggle.setAttribute('aria-label', isVisible ? 'Show password' : 'Hide password')", login)
        self.assertIn("passwordInput.focus()", login)

    def test_staged_minutes_analytics_tracks_server_recorded_review_signals(self):
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        analytics = (REPO_DIR / "views" / "staged-meeting-minutes-analytics.html").read_text(encoding="utf-8")

        self.assertIn("reviewSnapshot", staged_page)
        self.assertIn("discussionRowsFromReview", staged_page)
        self.assertIn("actionsFromReview", staged_page)
        self.assertIn("Review performance", analytics)
        self.assertIn("Reviews recorded", analytics)
        self.assertIn("Final reviews", analytics)
        self.assertIn("Changed fields", analytics)
        self.assertIn("Regenerations", analytics)
        self.assertIn("Terminology decisions", analytics)
        self.assertIn("Unresolved workstreams", analytics)
        self.assertIn("Edit types", analytics)
        self.assertIn("Where problems appear", analytics)
        self.assertIn("Recent recorded reviews", analytics)
        self.assertIn("initialiseStagedAnalyticsDashboard", analytics)
        self.assertIn("/api/staged-meeting-minutes/review-events?limit=500", analytics)
        self.assertIn("generated vs approved", analytics.lower())

    def test_staged_minutes_analytics_is_simple_current_progress_next_steps_dashboard(self):
        analytics = (REPO_DIR / "views" / "staged-meeting-minutes-analytics.html").read_text(encoding="utf-8")

        self.assertIn("Current performance", analytics)
        self.assertIn("Progress", analytics)
        self.assertIn("Next steps", analytics)
        self.assertIn("Server data connected", analytics)
        self.assertIn("Record a reviewed example", analytics)
        self.assertIn("Review recurring edit pattern", analytics)
        self.assertNotIn("prototype metrics layout", analytics.lower())
        self.assertNotIn("Estimated time saved", analytics)
        self.assertNotIn("111h", analytics)
        self.assertNotIn("Candidate improvements", analytics)
        self.assertNotIn("stagedMinutesImprovementApprovals", analytics)
        self.assertNotIn("Meeting search", analytics)
        self.assertNotIn("Commit e9b0019", analytics)

    def test_staged_minutes_pre_testing_dashboard_is_wired_to_core_golden_set(self):
        server = (REPO_DIR / "server.js").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        helper = (REPO_DIR / "utils" / "meetingMinutesCoreGolden.js").read_text(encoding="utf-8")
        page = (REPO_DIR / "views" / "staged-meeting-minutes-pre-testing.html").read_text(encoding="utf-8")
        dashboard = (REPO_DIR / "views" / "dashboard.html").read_text(encoding="utf-8")
        staged = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        analytics = (REPO_DIR / "views" / "staged-meeting-minutes-analytics.html").read_text(encoding="utf-8")

        self.assertIn("app.get('/staged-meeting-minutes/pre-testing', authRoutes.requireAuth", server)
        self.assertIn("router.get('/staged-meeting-minutes/pre-testing', requireAuth", api)
        self.assertIn("getMeetingMinutesCoreGoldenStatus", api)
        self.assertIn("scripts', 'meeting-minutes-core-golden", helper)
        self.assertIn("scoreCaseOutput", helper)
        self.assertIn("humanPerfectGap", helper)
        self.assertIn("previousRequiredEdits", helper)
        self.assertIn("currentRequiredEdits", helper)
        self.assertIn("requiredEditReduction", helper)
        self.assertIn("requiredEditTrend", helper)
        self.assertIn("buildRequiredEditTrend", helper)
        self.assertIn("Staged minutes pre-testing", page)
        self.assertIn("/api/staged-meeting-minutes/pre-testing", page)
        self.assertIn("Working", page)
        self.assertIn("Needs work", page)
        self.assertIn("Human-perfect gap", page)
        self.assertIn("Real edits across the 10-case suite", page)
        self.assertIn("Latest canonical run:", page)
        self.assertIn("currentIssueCount", page)
        self.assertIn("blockingIssueCount", page)
        self.assertIn("casesBelowFiveIssues", page)
        self.assertIn("requiredEditChart", page)
        self.assertIn("renderRequiredEditChart", page)
        self.assertIn("Benchmark pairs", page)
        self.assertIn('href="/staged-meeting-minutes/pre-testing"', dashboard)
        self.assertIn('href="/staged-meeting-minutes/pre-testing"', staged)
        self.assertIn('href="/staged-meeting-minutes/pre-testing"', analytics)

    def test_meeting_minutes_final_queue_and_jobs_page_are_wired(self):
        meeting_minutes_final = (REPO_DIR / "views" / "meeting-minutes-final.html").read_text(encoding="utf-8")
        jobs_page = (REPO_DIR / "views" / "meeting-minutes-jobs.html").read_text(encoding="utf-8")
        shared_js = (REPO_DIR / "public" / "test-transcript-page.js").read_text(encoding="utf-8")
        shared_css = (REPO_DIR / "public" / "trinzo.css").read_text(encoding="utf-8")
        server = (REPO_DIR / "server.js").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")

        self.assertIn("Process new meeting", jobs_page)
        self.assertIn("<h1>Library</h1>", jobs_page)
        self.assertIn('id="archiveAllBtn"', jobs_page)
        self.assertIn('id="archiveSelectedBtn"', jobs_page)
        self.assertIn('data-select-job=', jobs_page)
        self.assertIn('<th>Meeting</th>', jobs_page)
        self.assertIn('<th>Started</th>', jobs_page)
        self.assertNotIn('<th>Progress</th>', jobs_page)
        self.assertNotIn('<th>Runtime</th>', jobs_page)
        self.assertNotIn('<th>Attempts</th>', jobs_page)
        self.assertIn('.jobs-shell .bulk-bar', shared_css)
        self.assertIn("router.post('/jobs/archive'", api)
        self.assertIn("archiveGenerationJobs", db)
        self.assertIn("AND j.archived_at IS NULL", db)
        self.assertIn('class="jobs-page"', jobs_page)
        self.assertIn('class="jobs-header"', jobs_page)
        self.assertIn('class="jobs-actions"', jobs_page)
        self.assertIn('href="/jobs?type=staged-meeting-minutes">Staged meeting minutes</a>', jobs_page)
        self.assertNotIn('href="/jobs?type=meeting-minutes"', jobs_page)
        self.assertNotIn('href="/jobs?type=project-updates"', jobs_page)
        self.assertIn('href="/staged-meeting-minutes">Process new meeting</a>', jobs_page)
        self.assertIn('Resume staged review <span aria-hidden="true">›</span>', jobs_page)
        self.assertIn("body: JSON.stringify(allFinished ? { archiveAll: true }", jobs_page)
        self.assertIn('aria-label="Job queues"', jobs_page)
        self.assertIn("stagedMeetingMinutesJobs", jobs_page)
        self.assertIn("Resume staged review", jobs_page)
        self.assertIn("staged_meeting_minutes_review", jobs_page)
        self.assertIn("AI-generated staged screens run as backend jobs", jobs_page)
        self.assertIn("function isStaleStagedJob", jobs_page)
        self.assertIn("This staged generation is still in progress", jobs_page)
        self.assertIn("Resume will safely requeue the stage", jobs_page)
        self.assertIn("job.jobType === 'staged_meeting_minutes_stage' ? `<a class=\"button resume-staged\"", jobs_page)
        self.assertNotIn("New minutes", jobs_page)
        self.assertIn("data-expand-minutes-row>Open row</button>", jobs_page)
        self.assertNotIn("data-expand-minutes-row>Expand</button>", jobs_page)
        self.assertNotIn("Expanded row editor", jobs_page)
        self.assertIn("queuedEndpoint: '/api/meeting-minutes-final/jobs'", meeting_minutes_final)
        self.assertIn("jobsPageUrl: '/jobs'", meeting_minutes_final)
        self.assertIn("queuedEndpoint: '/api/project-update-test/jobs'", (REPO_DIR / "public" / "project-stage-process.js").read_text(encoding="utf-8"))
        self.assertIn("project-nav-link project-nav-primary", (REPO_DIR / "public" / "project-workspace.js").read_text(encoding="utf-8"))
        self.assertIn('href="/jobs"', meeting_minutes_final)
        self.assertIn('href="/jobs"', (REPO_DIR / "views" / "dashboard.html").read_text(encoding="utf-8"))
        self.assertIn('href="/jobs"', (REPO_DIR / "views" / "project-update-workspace.html").read_text(encoding="utf-8"))
        self.assertIn('href="/jobs"', (REPO_DIR / "views" / "project-update-reports.html").read_text(encoding="utf-8"))
        self.assertIn("config.queuedEndpoint", shared_js)
        self.assertIn("pollQueuedJob", shared_js)
        self.assertIn("window.location.assign(jobUrl)", shared_js)
        self.assertEqual(shared_js.count("let queuedNavigationStarted = false;"), 2)
        self.assertEqual(shared_js.count("queuedNavigationStarted = true;"), 2)
        self.assertEqual(shared_js.count("if (!queuedNavigationStarted) setLoading(false);"), 2)
        self.assertIn(".jobs td:nth-child(2)", (REPO_DIR / "public" / "trinzo.css").read_text(encoding="utf-8"))
        self.assertIn("table-layout:fixed", (REPO_DIR / "public" / "trinzo.css").read_text(encoding="utf-8"))
        self.assertIn("width:43%", (REPO_DIR / "public" / "trinzo.css").read_text(encoding="utf-8"))
        self.assertIn("Opening job #", shared_js)
        self.assertIn("app.get('/meeting-minutes-final/jobs'", server)
        self.assertIn("app.get('/meeting-minutes-final/jobs/:jobId'", server)
        self.assertIn("app.get('/meeting-minutes-final/jobs/:jobId/result'", server)
        self.assertIn("app.get('/jobs'", server)
        self.assertIn("app.get('/jobs/:jobId'", server)
        self.assertIn("app.get('/jobs/:jobId/result'", server)
        self.assertIn("app.get('/staged-meeting-minutes-analytics'", server)
        self.assertIn("router.post('/meeting-minutes-final/jobs'", api)
        self.assertIn("router.post('/staged-meeting-minutes'", api)
        self.assertIn("buildStagedMeetingMinutesResponse", api)
        self.assertIn("extractStagedDetailsFromTranscript", api)
        self.assertIn("cleanStagedMeetingTitleCandidate", api)
        self.assertIn("inferStagedMeetingType", api)
        self.assertIn("Webinar rehearsal", api)
        self.assertIn("formatReadableUkDate", api)
        self.assertIn("meeting\\s+transcript|transcript|recording", api)
        self.assertIn("20\\d{6}", api)
        self.assertIn("extractTeamsSpeakerNames", api)
        self.assertIn("allAttendees", api)
        self.assertIn("requestedStage === 'details'", api)
        self.assertIn("['summary', 'discussion', 'actions'].includes(requestedStage)", api)
        self.assertIn("canonicalStagedResponse(requestedStage", api)
        self.assertIn("runCanonicalLiveStage", api)
        canonical_live = (REPO_DIR / "utils" / "canonicalMinutes" / "liveStages.js").read_text(encoding="utf-8")
        self.assertIn("semanticStages.contextStage", canonical_live)
        self.assertIn("semanticStages.contentStage", canonical_live)
        self.assertIn("semanticStages.actionsStage", canonical_live)
        self.assertIn("loadMiniLMProfileSync", canonical_live)
        self.assertIn("humanConfirmedInputIsAuthoritative: true", canonical_live)
        self.assertIn("stage_1_human_confirmation", canonical_live)
        self.assertIn("stage_2_human_confirmation", canonical_live)
        self.assertIn("stage_3_human_confirmation", canonical_live)
        self.assertIn("overallTopics", api)
        self.assertIn("router.post('/project-update-test/jobs'", api)
        self.assertIn("router.get('/jobs'", api)
        self.assertIn("router.get('/jobs/:jobId'", api)
        self.assertIn("router.post('/jobs/:jobId/retry'", api)
        self.assertIn("router.post('/jobs/:jobId/cancel'", api)
        self.assertIn("router.delete('/jobs/:jobId'", api)
        self.assertIn("router.get('/meeting-minutes-final/jobs'", api)
        self.assertIn("router.get('/meeting-minutes-final/jobs/:jobId'", api)
        self.assertIn("router.patch('/meeting-minutes-final/jobs/:jobId/result'", api)
        self.assertIn("router.post('/meeting-minutes-final/jobs/:jobId/retry'", api)
        self.assertIn("router.post('/meeting-minutes-final/jobs/:jobId/cancel'", api)
        self.assertIn("router.delete('/meeting-minutes-final/jobs/:jobId'", api)
        self.assertIn("queueMeetingMinutesGeneration", db)
        self.assertIn("queueProjectUpdateGeneration", db)
        self.assertIn("project_update_generate", db)
        self.assertIn("claimNextGenerationJob", db)
        self.assertIn("updated_at < NOW() - INTERVAL '15 minutes'", db)
        self.assertIn("claimNextMeetingMinutesJob", db)
        self.assertIn("deleteMeetingMinutesJob", db)
        self.assertIn("updateMeetingMinutesJobResult", db)
        self.assertIn("includeProjectStatusEvidence", api)
        self.assertIn("includeProjectStatusEvidence", db)
        self.assertIn("--include-project-status-evidence", api)
        self.assertIn("--include-project-status-evidence", (REPO_DIR / "utils" / "meetingMinutesGenerator.js").read_text(encoding="utf-8"))
        self.assertIn("MEETING_MINUTES_PROJECT_STATUS_EVIDENCE", (REPO_DIR / "utils" / "meetingMinutesGenerator.js").read_text(encoding="utf-8"))
        self.assertIn("output.confirmedPoints", jobs_page)
        self.assertIn("output.risksAndIssues", jobs_page)
        self.assertIn("output.dependencies", jobs_page)
        self.assertIn("output.complianceFollowUps", jobs_page)
        self.assertIn("output.termsForReview", jobs_page)
        self.assertIn("Deadline / date", jobs_page)
        self.assertIn("Notes / context", jobs_page)
        self.assertNotIn("Status / detail", jobs_page)
        self.assertIn("data-edit-field=\"deadline\"", jobs_page)
        self.assertIn("Evidence / source note", jobs_page)
        self.assertIn("data-edit-field=\"detail\"", jobs_page)
        self.assertIn("data-edit-field=\"evidence\"", jobs_page)
        self.assertIn("'Risk / issue'", jobs_page)
        self.assertIn("'Compliance follow-up'", jobs_page)
        self.assertIn("'Term for review'", jobs_page)
        self.assertIn("meetingActionPointDeadline", jobs_page)
        self.assertIn("normalisedTerm", jobs_page)
        self.assertIn("sourceSnippet", jobs_page)
        self.assertIn("attempts = 0", db)
        self.assertIn("/api/jobs?limit=100", jobs_page)
        self.assertIn("window.location.pathname.match(/(?:\\/jobs|\\/meeting-minutes-final\\/jobs)", jobs_page)
        self.assertIn("Job cancellation requested", jobs_page)
        self.assertIn("Delete this job, stored transcript and generated result?", jobs_page)
        self.assertIn("Open result in new tab", jobs_page)
        self.assertIn('href="/jobs/${encodeURIComponent(job.jobId)}/result"', jobs_page)
        self.assertIn("renderReadableResult", jobs_page)
        self.assertIn("payload.result.output", jobs_page)
        self.assertIn("Raw result JSON", jobs_page)
        self.assertIn("Save edits", jobs_page)
        self.assertIn("data-edit-field", jobs_page)
        self.assertIn("data-meta-field", jobs_page)
        self.assertIn("editedMeta", jobs_page)
        self.assertIn("Client participants", jobs_page)
        self.assertIn("Trinzo participants", jobs_page)
        self.assertIn("Meeting objectives", jobs_page)
        self.assertIn("meetingLocation", jobs_page)
        self.assertIn("meetingLocationText", jobs_page)
        self.assertIn("Microsoft Teams", jobs_page)
        self.assertIn("discussionTopicLookup", jobs_page)
        self.assertIn("discussionTopics(output)", jobs_page)
        self.assertIn("addRowsFromDiscussionTopics", jobs_page)
        self.assertIn("data-edit-field=\"itemType\"", jobs_page)
        self.assertIn("addDiscussionRowsFromMeetingMinutes", jobs_page)
        self.assertIn("data-edit-field=\"topic\"", jobs_page)
        self.assertIn("<th>Topic</th>", jobs_page)
        self.assertIn("saveEditedResult", jobs_page)
        self.assertIn("queueAutosave", jobs_page)
        self.assertIn("Copy table text", jobs_page)
        self.assertIn("Download edited JSON", jobs_page)
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        staged_analytics_page = (REPO_DIR / "views" / "staged-meeting-minutes-analytics.html").read_text(encoding="utf-8")
        self.assertIn("stagedMeetingMinutesJobs", staged_page)
        self.assertIn('<body class="pre-upload">', staged_page)
        self.assertIn("body.pre-upload .status-strip", staged_page)
        self.assertIn("body:not(.pre-upload) .source-panel", staged_page)
        self.assertIn("review-only", staged_page)
        self.assertIn("function setReviewStarted", staged_page)
        self.assertIn("if (!reviewStarted && !lastGeneratedPayload) return;", staged_page)
        self.assertIn("setReviewStarted(true)", staged_page)
        self.assertIn("activeScreen", staged_page)
        self.assertIn("/api/staged-meeting-minutes", staged_page)
        self.assertIn("/api/staged-meeting-minutes/jobs?stage=", staged_page)
        self.assertIn("/api/staged-meeting-minutes/jobs?stage=' + encodeURIComponent(stage)", staged_page)
        self.assertIn("You can close this tab and resume from Library.", staged_page)
        self.assertIn("elapsedStageText", staged_page)
        self.assertIn('id="meetingLocation" placeholder="Microsoft Teams"', staged_page)
        self.assertIn('id="overallTopics"', staged_page)
        self.assertIn('id="reviewGenerationStatus"', staged_page)
        self.assertIn("overallTopicsInput", staged_page)
        self.assertIn("generatedStages", staged_page)
        self.assertIn("stagedState", staged_page)
        self.assertIn("function commitStageState", staged_page)
        self.assertIn("function applySavedStageState", staged_page)
        self.assertIn("confirmedDetails", staged_page)
        self.assertIn("confirmedSummary", staged_page)
        self.assertIn("confirmedDiscussion", staged_page)
        self.assertIn("confirmedActions", staged_page)
        self.assertIn("<option>Webinar rehearsal</option>", staged_page)
        self.assertIn("function highestReachableScreen", staged_page)
        self.assertIn("function stageNeedsGeneration", staged_page)
        self.assertIn("await requestStagedStage(stageForScreen(target), target)", staged_page)
        self.assertIn('id="regenerateScreenBtn"', staged_page)
        self.assertIn("Re-run AI generation step", staged_page)
        self.assertIn("This will overwrite everything currently on this screen", staged_page)
        self.assertIn("manual_ai_generation_rerun_overwrite", staged_page)
        self.assertIn("regenerationCount", staged_page)
        self.assertIn("regenerations", staged_page)
        self.assertIn("formData.append('meetingType'", staged_page)
        self.assertIn("formData.append('participants'", staged_page)
        self.assertIn("formData.append('overallTopics'", staged_page)
        self.assertIn("Date / deadline", staged_page)
        self.assertIn("Action date or deadline", staged_page)
        self.assertNotIn("Prefer an actual date", staged_page)
        self.assertIn("next Monday", staged_page)
        self.assertIn("<th>Owner</th><th>Action</th><th>Due</th>", staged_page)
        self.assertIn("escapeHtml(item.deadline || 'Not stated')", staged_page)
        self.assertNotIn("with no date stated", staged_page)
        self.assertIn("applyStagedPayload", staged_page)
        self.assertIn("function attendeeListsFromDetails", staged_page)
        self.assertIn("clientAttendees: attendeesFromRow(clientAttendeesRow)", staged_page)
        self.assertIn("checkbox-inline", staged_page)
        self.assertIn('.checkbox-inline input[type="checkbox"]', staged_page)
        self.assertIn("startReviewEditTimer", staged_page)
        self.assertIn("isReviewEditTarget", staged_page)
        self.assertIn("reviewEditStartedAt", staged_page)
        self.assertIn('class="discussion-table"', staged_page)
        self.assertIn("<th>Topic</th><th>Discussion points</th>", staged_page)
        self.assertNotIn("Hidden telemetry preview", staged_page)
        self.assertNotIn("Final report preview", staged_page)
        self.assertNotIn("telemetry-panel", staged_page)
        self.assertIn("discussion-card", staged_page)
        self.assertIn("discussion-card-chevron", staged_page)
        self.assertIn('data-lucide="chevron-down"', staged_page)
        self.assertIn('data-discussion-delete', staged_page)
        self.assertIn('data-lucide="trash-2"', staged_page)
        self.assertIn("Are you sure you want to remove this row?", staged_page)
        self.assertIn("commitStageState('discussion')", staged_page)
        self.assertIn('id="meetingPurpose"', staged_page)
        self.assertIn('id="keyFactsList"', staged_page)
        self.assertIn('id="actionReviewGroups"', staged_page)
        self.assertIn('data-generation-state', staged_page)
        self.assertIn('data-target-stage', staged_page)
        self.assertNotIn("What was discussed", staged_page)
        self.assertNotIn("Staging note:", staged_page)
        self.assertNotIn("Change owner", staged_page)
        self.assertIn('id="addActionRowBtn"', staged_page)
        self.assertIn('data-action-row="duplicate"', staged_page)
        self.assertIn('data-action-row="delete"', staged_page)
        self.assertIn("function formatUkDate", staged_page)
        self.assertIn("new Intl.DateTimeFormat('en-GB'", staged_page)
        self.assertIn("formatUkDate(details.meetingDate)", staged_page)
        self.assertIn("formData.append('pipeline', 'chunked')", staged_page)
        self.assertNotIn("API progress and client feedback review", staged_page)
        self.assertNotIn("Deployment readiness", staged_page)
        self.assertNotIn("Analytics and review confidence", staged_page)
        self.assertNotIn("stagedPipeline", staged_page)
        self.assertNotIn("Processing mode", staged_page)
        self.assertNotIn('id="meetingTime"', staged_page)
        self.assertIn("Regenerations", staged_analytics_page)
        self.assertIn("regenerationCount", staged_analytics_page)
        self.assertIn("Where problems appear", staged_analytics_page)
        self.assertIn("Manual AI re-runs", staged_analytics_page)
        self.assertIn("/api/staged-meeting-minutes/review-events?limit=500", staged_analytics_page)
        self.assertIn("editedMeta", api)
        self.assertIn("discussionTopics: editedDiscussionTopics", api)
        self.assertIn("meetingMinutes: editedMeetingMinutes", api)
        self.assertIn("itemType: String(row?.itemType", api)
        self.assertIn("topic: String(row?.topic", api)
        self.assertIn("detail: String(row?.detail", api)
        self.assertIn("evidence: String(row?.evidence", api)
        self.assertIn('"discussionTopics": [', (REPO_DIR / "scripts" / "meeting_minutes_trooper.py").read_text(encoding="utf-8"))

    def test_staged_action_candidate_flags_do_not_use_leaky_flag_index_scope(self):
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("function validationFlagKey(flag, index, stage)", staged_page)
        self.assertIn("function actionCandidateKey(flagKey, candidate)", staged_page)
        self.assertIn("var explicitKey = candidate && (candidate.id || candidate.key || candidate.candidateId)", staged_page)
        self.assertIn("function collectActionCandidatesFromFlags(list, stage)", staged_page)
        self.assertIn("function collectActionCandidatesFromPayload(candidates)", staged_page)
        self.assertIn("list.forEach(function (flag, flagIndex)", staged_page)
        self.assertIn("var flagKey = validationFlagKey(flag, flagIndex, stage)", staged_page)
        self.assertIn("fromFlags.concat(fromPayload).forEach(function (entry)", staged_page)
        self.assertNotIn("actionReviewCandidates.push({ id: flagIndex + '-' + candidateIndex", staged_page)

    def test_staged_action_candidates_are_persisted_and_hydrated(self):
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("var currentValidationFlags = []", staged_page)
        self.assertIn("var currentActionReviewCandidatePayloads = []", staged_page)
        self.assertIn("function compactValidationFlagsForDraft(flags)", staged_page)
        self.assertIn("validationFlags: compactValidationFlagsForDraft(currentValidationFlags)", staged_page)
        self.assertIn("validationStage: currentValidationStage", staged_page)
        self.assertIn("actionReviewCandidates: currentActionReviewCandidatePayloads", staged_page)
        self.assertIn("function actionCandidateAlreadyConfirmed(candidate)", staged_page)
        self.assertIn("function pruneConfirmedActionCandidates()", staged_page)
        self.assertIn("if (entry && actionCandidateAlreadyConfirmed(entry.candidate))", staged_page)
        self.assertIn("resolvedReviewCheckKeys[entry.id] = true", staged_page)
        self.assertIn("pruneConfirmedActionCandidates();", staged_page)
        self.assertIn("if (existing && Array.isArray(existing.validationFlags))", staged_page)
        self.assertIn("if (existing && Array.isArray(existing.actionReviewCandidates))", staged_page)
        self.assertIn("renderValidationFlags(currentValidationFlags, currentValidationStage || stageForScreen(activeIndex), currentActionReviewCandidatePayloads)", staged_page)
        self.assertIn("actionReviewCandidates = actionReviewCandidates.filter(function (entry) { return entry.id !== resolvedKey; })", staged_page)

    def test_staged_terminology_qa_covers_likely_action_candidates_and_is_collapsed(self):
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")
        terminology = (REPO_DIR / "utils" / "terminologyQa.js").read_text(encoding="utf-8")

        self.assertIn("actionCandidates: currentActionReviewCandidatePayloads", staged_page)
        self.assertIn("function actionCandidateIndexFromFieldPath(fieldPath)", staged_page)
        self.assertIn("function setActionCandidateTerminologyValue(fieldPath, value)", staged_page)
        self.assertIn("path: `actionCandidates.${index}.action`", terminology)
        self.assertIn("var details = document.createElement('details')", staged_page)
        self.assertIn("details.className = 'terminology-qa-details'", staged_page)
        self.assertNotIn("details.open = true", staged_page)

    def test_staged_final_review_only_shows_pdf_export_action(self):
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn('id="exportClientPdfBtn"', staged_page)
        self.assertNotIn('<button class="secondary" type="button" disabled>Copy</button>', staged_page)
        self.assertNotIn('<button class="secondary" type="button" disabled>Email</button>', staged_page)
        self.assertNotIn('<button class="secondary" type="button" disabled>Save draft</button>', staged_page)
        self.assertNotIn("Copy, Email and Save draft are not available yet.", staged_page)

    def test_resolved_workstream_flags_do_not_silently_block_actions_transition(self):
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("function unresolvedWorkstreamReviewKey(flag)", staged_page)
        self.assertIn("function reconcileUnresolvedWorkstreamFlags()", staged_page)
        self.assertIn("_reviewCheckKey: validationFlagKey(flag, flagIndex, currentValidationStage)", staged_page)
        self.assertIn("reconcileUnresolvedWorkstreamFlags();", staged_page)
        self.assertIn("if (activeIndex === 2 && reconcileUnresolvedWorkstreamFlags().length)", staged_page)
        self.assertNotIn("if (activeIndex === 2 && Object.keys(unresolvedWorkstreamFlags).length)", staged_page)

    def test_staged_generation_state_exposes_target_stage_and_terminal_states(self):
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn("var targetStageInFlight = ''", staged_page)
        self.assertIn("var generationState = 'idle'", staged_page)
        self.assertIn("function setGenerationState(state, targetStage)", staged_page)
        self.assertIn("document.body.setAttribute('data-target-stage', targetStageInFlight)", staged_page)
        self.assertIn("setGenerationState('queued', stage)", staged_page)
        self.assertIn("setGenerationState('running', stage)", staged_page)
        self.assertIn("setGenerationState('complete', '')", staged_page)
        self.assertIn("setGenerationState('error', stage)", staged_page)
        self.assertIn("idle = no generation in progress", staged_page)
        self.assertIn("complete = a generation request just succeeded", staged_page)
        self.assertIn("generationState: generationState", staged_page)
        self.assertIn("targetStage: targetStageInFlight", staged_page)
        self.assertIn("hydratingSavedDraft = true", staged_page)
        self.assertIn("if (hydratingSavedDraft) return", staged_page)

    def test_staged_discussion_controls_and_terminology_jump_are_wired_to_cards(self):
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        self.assertIn('id="expandDiscussionBtn"', staged_page)
        self.assertIn('id="collapseDiscussionBtn"', staged_page)
        self.assertIn("index === 0 ? ' open' : ''", staged_page)
        self.assertIn("document.querySelectorAll('.discussion-card')).forEach(function (card) { card.open = true; })", staged_page)
        self.assertIn("document.querySelectorAll('.discussion-card')).forEach(function (card) { card.open = false; })", staged_page)
        self.assertIn("function focusTerminologyControl(item)", staged_page)
        self.assertIn("discussionCard.open = true", staged_page)
        self.assertIn("jumpToField.textContent = 'Go to field'", staged_page)
        self.assertIn("discussionList.querySelectorAll('.discussion-card')[Number(parts[1])]", staged_page)

    def test_staged_review_items_are_connected_to_transition_and_autosave_is_visible(self):
        staged_page = (REPO_DIR / "views" / "staged-meeting-minutes.html").read_text(encoding="utf-8")

        decision_start = staged_page.index('<div class="stage-decision-card review-only"')
        decision_end = staged_page.index('</div>\n    </section>', decision_start)
        decision_markup = staged_page[decision_start:decision_end]
        self.assertIn('id="stageValidationFlags"', decision_markup)
        self.assertIn('id="resolvedChecks"', decision_markup)
        self.assertIn('id="reviewGenerationStatus"', decision_markup)
        self.assertGreaterEqual(staged_page.count('class="stage-autosave-status"'), 5)
        self.assertIn("function scheduleDraftAutosave()", staged_page)
        self.assertIn("Autosaved ' + date.toLocaleTimeString", staged_page)
        self.assertIn("scheduleDraftAutosave();", staged_page)


if __name__ == "__main__":
    unittest.main()
