import unittest
from pathlib import Path


REPO_DIR = Path(__file__).resolve().parents[1]


class FrontendContractTest(unittest.TestCase):
    def test_meeting_minutes_final_uses_date_picker_for_meeting_date(self):
        shared_js = (REPO_DIR / "public" / "test-transcript-page.js").read_text(encoding="utf-8")

        self.assertIn("function toDateInputValue", shared_js)
        self.assertIn('id="meetingDateInput" type="date"', shared_js)
        self.assertIn("toDateInputValue(schemaOutput.meetingDate)", shared_js)

    def test_feedback_widget_is_scoped_to_meeting_minutes_final(self):
        meeting_minutes_final = (REPO_DIR / "views" / "meeting-minutes-final.html").read_text(encoding="utf-8")
        dashboard = (REPO_DIR / "views" / "dashboard.html").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")

        self.assertIn('id="feedbackWidgetButton"', meeting_minutes_final)
        self.assertIn("/api/meeting-minutes-final/feedback", meeting_minutes_final)
        self.assertIn("Please avoid sharing transcript content", meeting_minutes_final)
        self.assertIn(".feedback-backdrop.hidden { display:none; }", meeting_minutes_final)
        self.assertNotIn("Please don’t paste transcripts or sensitive meeting details here.", meeting_minutes_final)
        self.assertNotIn('id="feedbackEmail"', meeting_minutes_final)
        self.assertNotIn('id="feedbackWidgetButton"', dashboard)
        self.assertIn("router.post('/meeting-minutes-final/feedback'", api)
        self.assertIn("saveMeetingMinutesFeedback", api)
        self.assertIn("meeting_minutes_feedback", db)
        self.assertNotIn("transcriptText", api.split("router.post('/meeting-minutes-final/feedback'", 1)[1].split("router.post('/project-update-test'", 1)[0])

    def test_snippet_level_feedback_and_ai_shortcuts_are_wired(self):
        meeting_minutes_final = (REPO_DIR / "views" / "meeting-minutes-final.html").read_text(encoding="utf-8")
        shared_js = (REPO_DIR / "public" / "test-transcript-page.js").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")

        self.assertIn("snippetImproveEndpoint: '/api/meeting-minutes-final/improve-snippet'", meeting_minutes_final)
        self.assertIn('id="feedbackSnippetQuote"', meeting_minutes_final)
        self.assertIn("event.key.toLowerCase() === 'f'", meeting_minutes_final)
        self.assertIn("Selected snippet for this feedback", meeting_minutes_final)
        self.assertIn("What should change about the selected snippet?", meeting_minutes_final)
        self.assertIn("selectedSnippet: currentSnippet", meeting_minutes_final)
        self.assertNotIn("Feedback about selected snippet", meeting_minutes_final)
        self.assertIn("function getEditableSnippetSelection", shared_js)
        self.assertIn("Ctrl+Shift+M (Cmd+Shift+M on Mac)", shared_js)
        self.assertIn("selection.replace(improved)", shared_js)
        self.assertIn("router.post('/meeting-minutes-final/improve-snippet'", api)
        self.assertIn("selectedSnippet: selectedSnippet || null", api)
        self.assertIn("meeting_minutes_rewrite_snippet.py", api)

    def test_feedback_listing_is_authenticated_and_editable(self):
        server = (REPO_DIR / "server.js").read_text(encoding="utf-8")
        auth = (REPO_DIR / "routes" / "auth.js").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")
        listing = (REPO_DIR / "views" / "meeting-minutes-feedback.html").read_text(encoding="utf-8")
        login = (REPO_DIR / "views" / "auth-login.html").read_text(encoding="utf-8")

        self.assertIn("app.get('/meeting-minutes-feedback', authRoutes.requireAuth", server)
        self.assertIn("router.requireAuth = requireAuth", auth)
        self.assertIn("router.get('/meeting-minutes-final/feedback-submissions', requireAuth", api)
        self.assertIn("router.patch('/meeting-minutes-final/feedback-submissions/:feedbackId', requireAuth", api)
        self.assertIn("router.delete('/meeting-minutes-final/feedback-submissions/:feedbackId', requireAuth", api)
        self.assertIn("listMeetingMinutesFeedback", db)
        self.assertIn("updateMeetingMinutesFeedback", db)
        self.assertIn("deleteMeetingMinutesFeedback", db)
        feedback_list_section = db.split("async function listMeetingMinutesFeedback", 1)[1].split("async function getMeetingMinutesFeedback", 1)[0]
        feedback_detail_section = db.split("async function getMeetingMinutesFeedback", 1)[1].split("async function updateMeetingMinutesFeedback", 1)[0]
        feedback_delete_section = db.split("async function deleteMeetingMinutesFeedback", 1)[1].split("async function getMeetingStatus", 1)[0]
        self.assertIn("LIMIT $1", feedback_list_section)
        self.assertIn("WHERE id = $1", feedback_detail_section)
        self.assertIn("WHERE id = $1 RETURNING id", feedback_delete_section)
        self.assertNotIn("LIMIT ${safeLimit}", feedback_list_section)
        self.assertNotIn("WHERE id = ${id}", feedback_detail_section)
        self.assertNotIn("WHERE id = ${id}", feedback_delete_section)
        self.assertIn("isActive === 't' || isActive === 'true'", db)
        self.assertIn("selectedSnippet", db)
        self.assertIn("claire_comments", db)
        self.assertIn("fix_details", db)
        self.assertIn("/api/meeting-minutes-final/feedback-submissions", listing)
        self.assertIn("Comments from Claire", listing)
        self.assertIn("Fix details", listing)
        self.assertIn("delete-feedback", listing)
        self.assertIn("This action cannot be undone, are you sure you want to delete the feedback?", listing)
        self.assertIn("details class=\"technical-context\"", listing)
        self.assertIn("<summary><h2>Technical context</h2></summary>", listing)
        self.assertIn("Self-registration is disabled", auth)
        self.assertIn("res.redirect('/auth/login')", server)
        self.assertNotIn("Create account", login)
        self.assertNotIn("/auth/register", login)

    def test_dashboard_only_links_to_feedback_listing_and_matches_final_style(self):
        dashboard = (REPO_DIR / "views" / "dashboard.html").read_text(encoding="utf-8")
        meeting_minutes_final = (REPO_DIR / "views" / "meeting-minutes-final.html").read_text(encoding="utf-8")
        shared_nav = (REPO_DIR / "public" / "trinzo.js").read_text(encoding="utf-8")

        shared_style_tokens = ["--bg:#0b1020", "--panel:#11192f", "--accent:#17D0C4", "linear-gradient(145deg,var(--panel),var(--panel2))"]
        for token in shared_style_tokens:
            self.assertIn(token, dashboard)
            self.assertIn(token, meeting_minutes_final)

        self.assertIn("Project Updates", shared_nav)
        self.assertIn("Choose project", shared_nav)
        self.assertNotIn("Choose a project", shared_nav)
        self.assertIn('href="/meeting-minutes-feedback"', dashboard)
        self.assertIn("Open feedback listing", dashboard)
        self.assertNotIn('href="/"', dashboard)
        self.assertNotIn('href="/review"', dashboard)
        self.assertNotIn('href="/meetings"', dashboard)
        self.assertNotIn('href="/auth"', dashboard)
        self.assertNotIn("Transcript workflow", dashboard)
        self.assertNotIn("Review editor", dashboard)
        self.assertNotIn("Meeting manager", dashboard)
        self.assertNotIn("Auth center", dashboard)


    def test_meeting_minutes_golden_eval_defaults_to_live_trooper_route(self):
        runner = (REPO_DIR / "scripts" / "run_meeting_minutes_final_golden_eval.py").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        readme = (REPO_DIR / "scripts" / "meeting-minutes-final-golden" / "README.md").read_text(encoding="utf-8")
        runbook = (REPO_DIR / "scripts" / "meeting-minutes-final-golden" / "RUNBOOK.md").read_text(encoding="utf-8")

        self.assertIn("runPythonTranscriptScript('meeting_minutes_trooper.py'", api)
        self.assertIn('DEFAULT_EXTRACTOR_NAME = "meeting_minutes_trooper.py"', runner)
        self.assertIn('meeting_minutes_trooper.py', readme)
        self.assertIn('meeting_minutes_trooper.py', runbook)
        default_section = runner.split('DEFAULT_EXTRACTOR_NAME', 1)[1].split('REQUIRED_CATEGORIES', 1)[0]
        self.assertNotIn('meeting_minutes_final_colab.py', default_section)

    def test_login_removes_forgot_password_and_secure_auth_copy(self):
        login = (REPO_DIR / "views" / "auth-login.html").read_text(encoding="utf-8")

        self.assertNotIn("Forgot password", login)
        self.assertNotIn("/auth/forgot-password", login)
        self.assertNotIn("Trinzo secure authentication", login)

    def test_login_password_visibility_toggle_is_wired(self):
        login = (REPO_DIR / "views" / "auth-login.html").read_text(encoding="utf-8")

        self.assertIn('class="password-input"', login)
        self.assertIn('id="passwordToggle"', login)
        self.assertIn('type="button"', login)
        self.assertIn('aria-label="Show password"', login)
        self.assertIn('aria-pressed="false"', login)
        self.assertIn("passwordInput.type = isVisible ? 'password' : 'text'", login)
        self.assertIn("passwordToggle.setAttribute('aria-label', isVisible ? 'Show password' : 'Hide password')", login)
        self.assertIn("passwordInput.focus()", login)

    def test_meeting_minutes_final_queue_and_jobs_page_are_wired(self):
        meeting_minutes_final = (REPO_DIR / "views" / "meeting-minutes-final.html").read_text(encoding="utf-8")
        jobs_page = (REPO_DIR / "views" / "meeting-minutes-jobs.html").read_text(encoding="utf-8")
        shared_js = (REPO_DIR / "public" / "test-transcript-page.js").read_text(encoding="utf-8")
        server = (REPO_DIR / "server.js").read_text(encoding="utf-8")
        api = (REPO_DIR / "routes" / "api.js").read_text(encoding="utf-8")
        db = (REPO_DIR / "utils" / "db.js").read_text(encoding="utf-8")

        self.assertIn("Process new meeting", jobs_page)
        self.assertIn("<h1>Jobs</h1>", jobs_page)
        self.assertIn('class="jobs-page"', jobs_page)
        self.assertIn('class="jobs-header"', jobs_page)
        self.assertIn('class="jobs-actions"', jobs_page)
        self.assertIn('href="/jobs?type=project-updates">Project updates</a>', jobs_page)
        self.assertIn('aria-label="Job queues"', jobs_page)
        self.assertNotIn("New minutes", jobs_page)
        self.assertIn("data-expand-minutes-row>Open row</button>", jobs_page)
        self.assertNotIn("data-expand-minutes-row>Expand</button>", jobs_page)
        self.assertNotIn("Expanded row editor", jobs_page)
        self.assertIn("queuedEndpoint: '/api/meeting-minutes-final/jobs'", meeting_minutes_final)
        self.assertIn("jobsPageUrl: '/jobs'", meeting_minutes_final)
        self.assertIn("queuedEndpoint: '/api/project-update-test/jobs'", (REPO_DIR / "public" / "project-stage-process.js").read_text(encoding="utf-8"))
        self.assertIn("project-nav-link project-nav-primary", (REPO_DIR / "public" / "project-workspace.js").read_text(encoding="utf-8"))
        self.assertIn('href="/jobs"', meeting_minutes_final)
        self.assertIn('href="/jobs"', (REPO_DIR / "views" / "dashboard.html").read_text(encoding="utf-8"))
        self.assertIn('href="/jobs"', (REPO_DIR / "views" / "project-update-workspace.html").read_text(encoding="utf-8"))
        self.assertIn('href="/jobs"', (REPO_DIR / "views" / "project-update-reports.html").read_text(encoding="utf-8"))
        self.assertIn("config.queuedEndpoint", shared_js)
        self.assertIn("pollQueuedJob", shared_js)
        self.assertIn("window.location.assign(jobUrl)", shared_js)
        self.assertIn("Opening job #", shared_js)
        self.assertIn("app.get('/meeting-minutes-final/jobs'", server)
        self.assertIn("app.get('/meeting-minutes-final/jobs/:jobId'", server)
        self.assertIn("app.get('/meeting-minutes-final/jobs/:jobId/result'", server)
        self.assertIn("app.get('/jobs'", server)
        self.assertIn("app.get('/jobs/:jobId'", server)
        self.assertIn("app.get('/jobs/:jobId/result'", server)
        self.assertIn("router.post('/meeting-minutes-final/jobs'", api)
        self.assertIn("router.post('/project-update-test/jobs'", api)
        self.assertIn("router.get('/jobs'", api)
        self.assertIn("router.get('/jobs/:jobId'", api)
        self.assertIn("router.post('/jobs/:jobId/retry'", api)
        self.assertIn("router.post('/jobs/:jobId/cancel'", api)
        self.assertIn("router.delete('/jobs/:jobId'", api)
        self.assertIn("router.get('/meeting-minutes-final/jobs'", api)
        self.assertIn("router.get('/meeting-minutes-final/jobs/:jobId'", api)
        self.assertIn("router.patch('/meeting-minutes-final/jobs/:jobId/result'", api)
        self.assertIn("router.post('/meeting-minutes-final/jobs/:jobId/retry'", api)
        self.assertIn("router.post('/meeting-minutes-final/jobs/:jobId/cancel'", api)
        self.assertIn("router.delete('/meeting-minutes-final/jobs/:jobId'", api)
        self.assertIn("queueMeetingMinutesGeneration", db)
        self.assertIn("queueProjectUpdateGeneration", db)
        self.assertIn("project_update_generate", db)
        self.assertIn("claimNextGenerationJob", db)
        self.assertIn("claimNextMeetingMinutesJob", db)
        self.assertIn("deleteMeetingMinutesJob", db)
        self.assertIn("updateMeetingMinutesJobResult", db)
        self.assertIn("includeProjectStatusEvidence", api)
        self.assertIn("includeProjectStatusEvidence", db)
        self.assertIn("--include-project-status-evidence", api)
        self.assertIn("--include-project-status-evidence", (REPO_DIR / "utils" / "meetingMinutesGenerator.js").read_text(encoding="utf-8"))
        self.assertIn("MEETING_MINUTES_PROJECT_STATUS_EVIDENCE", (REPO_DIR / "utils" / "meetingMinutesGenerator.js").read_text(encoding="utf-8"))
        self.assertIn("output.confirmedPoints", jobs_page)
        self.assertIn("output.risksAndIssues", jobs_page)
        self.assertIn("output.dependencies", jobs_page)
        self.assertIn("output.complianceFollowUps", jobs_page)
        self.assertIn("output.termsForReview", jobs_page)
        self.assertIn("Deadline / date", jobs_page)
        self.assertIn("Notes / context", jobs_page)
        self.assertNotIn("Status / detail", jobs_page)
        self.assertIn("data-edit-field=\"deadline\"", jobs_page)
        self.assertIn("Evidence / source note", jobs_page)
        self.assertIn("data-edit-field=\"detail\"", jobs_page)
        self.assertIn("data-edit-field=\"evidence\"", jobs_page)
        self.assertIn("'Risk / issue'", jobs_page)
        self.assertIn("'Compliance follow-up'", jobs_page)
        self.assertIn("'Term for review'", jobs_page)
        self.assertIn("meetingActionPointDeadline", jobs_page)
        self.assertIn("normalisedTerm", jobs_page)
        self.assertIn("sourceSnippet", jobs_page)
        self.assertIn("attempts = 0", db)
        self.assertIn("/api/jobs?limit=100", jobs_page)
        self.assertIn("window.location.pathname.match(/(?:\\/jobs|\\/meeting-minutes-final\\/jobs)", jobs_page)
        self.assertIn("Job cancellation requested", jobs_page)
        self.assertIn("Delete this job, stored transcript and generated result?", jobs_page)
        self.assertIn("Open result in new tab", jobs_page)
        self.assertIn('href="/jobs/${encodeURIComponent(job.jobId)}/result"', jobs_page)
        self.assertIn("renderReadableResult", jobs_page)
        self.assertIn("payload.result.output", jobs_page)
        self.assertIn("Raw result JSON", jobs_page)
        self.assertIn("Save edits", jobs_page)
        self.assertIn("data-edit-field", jobs_page)
        self.assertIn("data-meta-field", jobs_page)
        self.assertIn("editedMeta", jobs_page)
        self.assertIn("Client participants", jobs_page)
        self.assertIn("Trinzo participants", jobs_page)
        self.assertIn("Meeting objectives", jobs_page)
        self.assertIn("meetingLocation", jobs_page)
        self.assertIn("meetingLocationText", jobs_page)
        self.assertIn("Microsoft Teams", jobs_page)
        self.assertIn("discussionTopicLookup", jobs_page)
        self.assertIn("discussionTopics(output)", jobs_page)
        self.assertIn("addRowsFromDiscussionTopics", jobs_page)
        self.assertIn("data-edit-field=\"itemType\"", jobs_page)
        self.assertIn("addDiscussionRowsFromMeetingMinutes", jobs_page)
        self.assertIn("data-edit-field=\"topic\"", jobs_page)
        self.assertIn("<th>Topic</th>", jobs_page)
        self.assertIn("saveEditedResult", jobs_page)
        self.assertIn("queueAutosave", jobs_page)
        self.assertIn("Copy table text", jobs_page)
        self.assertIn("Download edited JSON", jobs_page)
        self.assertIn("editedMeta", api)
        self.assertIn("discussionTopics: editedDiscussionTopics", api)
        self.assertIn("meetingMinutes: editedMeetingMinutes", api)
        self.assertIn("itemType: String(row?.itemType", api)
        self.assertIn("topic: String(row?.topic", api)
        self.assertIn("detail: String(row?.detail", api)
        self.assertIn("evidence: String(row?.evidence", api)
        self.assertIn('"discussionTopics": [', (REPO_DIR / "scripts" / "meeting_minutes_trooper.py").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
