'use strict';

// Topic-label baseline across the transcript corpus.
//
// The parse-invariance harness guards prepareEvidence(); this guards what a
// reviewer actually reads at the top of the discussion screen. Topic labels are
// generated by several functions with different guards, so a change to any one
// of them needs to be seen against every committed transcript rather than the
// one that prompted it.
//
// Unlike the parse baseline this is not an invariance check: topic wording is
// expected to change when the editorial rules change. It exists so that the
// change can be read line by line and judged, and so that a rule which empties
// a meeting's discussion cannot land unnoticed.
//
// Capture:  node scripts/topic_label_baseline.js --write
// Compare:  node scripts/topic_label_baseline.js
//
// Each run spawns the MiniLM profiler per transcript, so a full pass is slow
// and CPU-heavy. Run it with nice on a shared machine.

const fs = require('fs');
const path = require('path');
const { listTranscripts, readTranscript } = require('./evidence_parse_baseline');
const { runCanonicalLiveStage } = require('../utils/canonicalMinutes/liveStages');

const REPO_ROOT = path.resolve(__dirname, '..');
const BASELINE_PATH = path.join(REPO_ROOT, 'tests', 'fixtures', 'topic-label-baseline.json');

// Both screens a reviewer reads topic names on. They are produced by different
// code with different guards, so a change to either has to be seen against the
// whole corpus, and a change aimed at one must not quietly reshape the other.
function runStage(text, stage, file) {
  return runCanonicalLiveStage(text, { stage, fileName: path.basename(file), confirmed: {}, includeEvidencePack: false });
}

async function collectTopics() {
  const rows = [];
  for (const file of listTranscripts()) {
    let topics = [];
    let summaryTopics = [];
    let error = null;
    try {
      const text = await readTranscript(file);
      topics = (runStage(text, 'discussion', file)?.screens?.discussion || []).map((entry) => entry.topic).filter(Boolean);
      summaryTopics = (runStage(text, 'summary', file)?.screens?.summary?.overallTopics || []).filter(Boolean);
    } catch (failure) {
      error = failure.message;
    }
    rows.push({ file, topicCount: topics.length, topics, summaryTopicCount: summaryTopics.length, summaryTopics, ...(error ? { error } : {}) });
  }
  return rows;
}

const readBaseline = () => JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'));

const SCREENS = [
  { key: 'topics', countKey: 'topicCount', label: 'discussion' },
  { key: 'summaryTopics', countKey: 'summaryTopicCount', label: 'summary' }
];

function diffAgainstBaseline(rows, baseline) {
  const after = new Map(rows.map((row) => [row.file, row]));
  const changes = [];
  for (const before of baseline) {
    const now = after.get(before.file);
    if (!now) continue;
    for (const screen of SCREENS) {
      const was = before[screen.key] || [];
      const is = now[screen.key] || [];
      const removed = was.filter((topic) => !is.includes(topic));
      const added = is.filter((topic) => !was.includes(topic));
      if (removed.length || added.length) {
        changes.push({ file: before.file, screen: screen.label, removed, added, emptied: was.length > 0 && is.length === 0 });
      }
    }
  }
  return changes;
}

function report(rows, baseline) {
  const changes = diffAgainstBaseline(rows, baseline);
  const emptied = changes.filter((change) => change.emptied);
  console.log(`transcripts            : ${rows.length}`);
  console.log(`screen changes         : ${changes.length}`);
  for (const screen of SCREENS) {
    const forScreen = changes.filter((change) => change.screen === screen.label);
    console.log(`  ${screen.label.padEnd(11)}: ${forScreen.reduce((sum, change) => sum + change.removed.length, 0)} removed, ${forScreen.reduce((sum, change) => sum + change.added.length, 0)} added, across ${forScreen.length} transcripts`);
  }
  console.log(`emptied a screen       : ${emptied.length}${emptied.length ? '  <-- each needs a reason' : ''}`);
  for (const change of changes) {
    console.log(`\n${change.file}  [${change.screen}]${change.emptied ? '   *** EMPTIED ***' : ''}`);
    change.removed.forEach((topic) => console.log(`  - ${topic}`));
    change.added.forEach((topic) => console.log(`  + ${topic}`));
  }
  return changes;
}

async function main() {
  const rows = await collectTopics();
  if (process.argv.includes('--write')) {
    fs.mkdirSync(path.dirname(BASELINE_PATH), { recursive: true });
    fs.writeFileSync(BASELINE_PATH, `${JSON.stringify(rows, null, 2)}\n`);
    const total = rows.reduce((sum, row) => sum + row.topicCount, 0);
    console.log(`wrote ${path.relative(REPO_ROOT, BASELINE_PATH)}: ${rows.length} transcripts, ${total} topics`);
    return;
  }
  if (!fs.existsSync(BASELINE_PATH)) { console.log('no baseline captured yet; run with --write'); return; }
  report(rows, readBaseline());
}

module.exports = { collectTopics, readBaseline, diffAgainstBaseline, BASELINE_PATH };

if (require.main === module) main().catch((error) => { console.error(error); process.exitCode = 1; });
